CODE_OF_CONDUCT.md
README.md
SECURITY.md
SUPPORT.md

Added SECURITY.md and SUPPORT.md
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

Added SECURITY.md, Code_of_conduct and SUPPORT.md

---

conf/script/ha_setup

- Resolve provision dependency
- Disable failback causing consul dependency fail
<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

failback_disable: Disable failback

---

conf/script/build-ha-io

Patch that was previously merged to cortx-1.0 is modified for main branch.
See: https://github.com/Seagate/cortx-ha/pull/134

Problem: S3 resources do not stop when motr stack migrated to another node

---

conf/script/ha_setup

<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

consul_dependency_fix: Fix consul dependency

---

README.md

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
Add Codacy health badge.

Refactor: modify codacy badge url

---

ha/resource/sspl

<pre>
<code>
Improve sleep for promote
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Fix sleep time for sspl ra

---

conf/script/build-ha-io

Cherry-pick to cortx-1.0 from pull request #196.

Problem: ClusterIP resource may sporadically fail and migrate to another node (#196)

---

conf/setup.yaml
ha/cli/commands.py
ha/const.py
ha/core/cluster/cluster_manager.py
ha/core/error.py
ha/core/support_bundle/ha_bundle.py

- Provided support bundle command
<pre>
<code>
https://jts.seagate.com/browse/EOS-14006
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Support bundle for ha is missing causing difficult to debug.
</code>
</pre>
<pre>
<code>
Provide new cli for support bundle.
**$ cortxha support_bundle create 1 /tmp**
</code>
</pre>
<pre>
<code>
Unit testing is not added in HA WIP.
Integration Testing Done.
</code>
</pre>

Added new command support_bundle

---

conf/script/ha_setup
ha/resource/resource_agent.py

**Metadata still giving problem but return code improved**
<pre>
<code>
EOS-13879
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Metadata for m4 failing
</code>
</pre>
<pre>
<code>
Not working any solution but return code corrected
</code>
</pre>
<pre>
<code>
No unit testing
</code>
</pre>

metadata: Fix return code for metadata

---

conf/script/build-ha-io

<pre>
<code>
To reduce failover/failback time kill m0d processes
</code>
</pre>
<pre>
<code>
Tested on HW
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

[EOS-14191] To reduce failover/failback time kill m0d processes

---

conf/script/build-ha-update

This should help to debug the problems with missing data in Consul.
(cherry picked from commit c2b2931266c6647de3ed57a87c41178aa455c772)

build-ha-update: archive consul-kv-dump.json files (#218)

---

conf/script/build-ha-sspl
conf/script/ha_setup

<pre>
<code>
https://jts.seagate.com/browse/EOS-14558
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Change consul path changing to /usr/bin/
</code>
</pre>
<pre>
<code>
change path from repo
</code>
</pre>
<pre>
<code>
No unit testing
</code>
</pre>

Change consul path to /usr/bin/consul

---

conf/script/build-ha-sspl
conf/script/ha_setup

<pre>
<code>
https://jts.seagate.com/browse/EOS-14558
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Change consul path changing to /usr/bin/
</code>
</pre>
<pre>
<code>
change path from repo
</code>
</pre>
<pre>
<code>
No unit testing
</code>
</pre>

Replace consul path to /usr/bin/consul

---

conf/script/build-ha-update

<pre>
<code>
https://jts.seagate.com/browse/EOS-14611
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Just a syntax error in bash script. If expression in bash requires `if ... ; then ; fi` rather than `if ... ; do ; done`
</code>
</pre>
<pre>
<code>
Fix the if expression.
</code>
</pre>
<pre>
<code>
None
</code>
</pre>

EOS-14611: fix syntax error in bash script

---

conf/script/build-ha-update

Note: this is cortx-1.0 version of https://github.com/Seagate/cortx-ha/pull/228
<pre>
<code>
https://jts.seagate.com/browse/EOS-14611
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Just a syntax error in bash script. If expression in bash requires `if ... ; then ; fi` rather than `if ... ; do ; done`
</code>
</pre>
<pre>
<code>
Fix the bash script
</code>
</pre>
<pre>
<code>
N/A
</code>
</pre>

EOS-14611: Fix bash syntax error (cortx-1.0)

---

ha/core/node/replacement/refresh_context.py

<pre>
<code>
https://jts.seagate.com/browse/EOS-14683
cluster stuck in cycle
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Here, 
cortxha node refresh --soft
command was checking all alert are resolved and doing cleanup but not ack,
if there is some software and hw error seen then due to cleanup cluster trying to recover after hw alert resolved
but again doing failover due to software error.
As alert is not ack cortxha will try to cleanup cluster again which will create cycle.
</code>
</pre>
<pre>
<code>
Ack alert and perform cleanup to avoid cycle
</code>
</pre>
<pre>
<code>
Unit Testing details …

failback_ack_fix: Ack resource during failback

---

ha/core/node/replacement/refresh_context.py

<pre>
<code>
https://jts.seagate.com/browse/EOS-14683
cluster stuck in cycle
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Here, 
cortxha node refresh --soft
command was checking all alert are resolved and doing cleanup but not ack,
if there is some software and hw error seen then due to cleanup cluster trying to recover after hw alert resolved
but again doing failover due to software error.
As alert is not ack cortxha will try to cleanup cluster again which will create cycle.
</code>
</pre>
<pre>
<code>
Ack alert and perform cleanup to avoid cycle
</code>
</pre>
<pre>
<code>
Unit Testing details …

failback_ack_fix_main: Ack alert and perform cleanup in failback

---

conf/etc/ha.conf
conf/script/ha_setup
ha/alert/pcs/alert_generator.py

<pre>
<code>
https://jts.seagate.com/browse/EOS-14461
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Showing minion id on GUI will confuse user to get node problem.
</code>
</pre>
<pre>
<code>
Map hostname and node minion id and use hostname to alert.
</code>
</pre>
<pre>
<code>
No unit testing provided but done integration testing.
</code>
</pre>

host_minion_map: Map minion id with hostname

---

conf/script/ha_setup

<pre>
<code>
https://jts.seagate.com/browse/EOS-14765
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Deployment failing for ha as consul dir not available
</code>
</pre>
<pre>
<code>
Unwanted dir failing build
Remove dir related code
This dir only available for vm 
</code>
</pre>
<pre>
<code>
No unit testing but done testing with RPM.
</code>
</pre>

Hot Fix: consul watcher break

---

CODEOWNERS

Adding new code owner to cortx-ha repository.

New code owner

---

conf/script/build-cortx-ha
conf/script/build-ha-csm
conf/script/build-ha-io
conf/script/build-ha-sspl
conf/script/build-ha-uds
conf/script/build-ha-update
conf/script/prov-ha-csm-reset
conf/script/prov-ha-reset
conf/script/prov-ha-sspl-reset
conf/script/prov-ha-uds-reset
conf/script/prov-m0-reset

<pre>
<code>
Logging is missing for the HA build and reset scripts 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Logging is missing for the HA build and reset scripts 
</code>
</pre>
<pre>
<code>
Logging added to the files 
</code>
</pre>
<pre>
<code>
For testing, custom build will be created with the changes and will be deployed on hardware 
</code>
</pre>

changes for EOS-15135 Add logging to build-ha-* scripts 

---

SUPPORT.md

Updated Support.md
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

Updated Support.md

---

jenkins/cicd/cortx-ha-cicd.sh
jenkins/cicd/cortx-ha-dep.sh
jenkins/rpm/v2/cortx-ha.spec

<pre>
<code>
Story Ref (if any): EOS-16536
After merge of packaging story PR, build was failing
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
After merge of packaging story PR, build was failing. We changes the path of spec and requirements files, hence we need those changes in jenkins/cicd/cortx-ha-cicd.sh and jenkins/cicd/cortx-ha-dep.sh
</code>
</pre>
<pre>
<code>
- We did change the path of requirements.txt file path in jenkins/cicd/cortx-ha-dep.sh
- We did pass the version -v parameter to the script jenkins/cicd/cortx-ha-dep.sh to compare the HA1 and HA2 versions and using the requirements files accordingly from v1 & v2 directory.
- We did change in jenkins/cicd/cortx-ha-cicd.sh file to read VERSION from ha.conf file and based on version we are executing the unit tests. …

EOS-16536 fix build issues

---

README.md

Added the Slack Channel and YouTube Badge to the file.

Added the Slack and YouTube badges

---

ha/cli/cortxha.py
ha/const.py
ha/core/cluster/cluster_manager.py
ha/core/config/config_manager.py

<pre>
<code>
This PR is for implementation of cortxha cluster start CLI for M0
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Code added for cortxha cluster start CLI
</code>
</pre>
<pre>
<code>
Code added for cortxha cluster start CLI
</code>
</pre>
<pre>
<code>
A 2 node cluster created on VMs
Verified that the cluster starts correctly in following cases 
- pcs was not installed on the node/VM : [Output] Error displayed
- cluster was in stopped state on the node/VM : [Output] Cluster started successfully
- cluster was already started on both nodes/VMs: [Output] Nothing was done  
- cluster was running but both nodes/VMs were in standby:[Output] Cluster started successfully; nodes made Online
- both nodes/VMs were Offline and cluster was stopped on both nodes:[Output] Cluster …

Changes for EOS-16466 ECS-HA : M0 specific implementation of "cortxha cluster start" CLI

---

ha/setup/create_pacemaker_resources.py

<pre>
<code>
Resource definition failing during resource creation
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Resource definition failing during resource creation
</code>
</pre>
<pre>
<code>
Resource definition failing during resource creation
Solution is to fix defination
</code>
</pre>
<pre>
<code>
No testing  </code>
</pre>

Fix haproxy resource configuration

---

ha/core/cluster/cluster_manager.py

<pre>
<code>
true / false strings are used instead of boolean variables in the code 
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
true / false strings are used instead of boolean variables in the code 
</code>
</pre>
<pre>
<code>
Modified the true /false strings  to booleans
</code>
</pre>
<pre>
<code>
confirmed that the functionality remains unchanged after the string to boolean replacement
</code>
</pre>

Changes for EOS-17121 Change true/false values from strings to boolean

---

ha/resource/dynamic_fid_service_ra.py
ha/setup/create_pacemaker_resources.py

<pre>
<code>
Default instance is not set. Thus, "motr-confd" failing as expecting "motr-confd-1" where 1 is instance
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Default instance is not set. Thus, "motr-confd" failing as expecting "motr-confd-1" where 1 is instance
</code>
</pre>
<pre>
<code>
set default instance to 1
</code>
</pre>
<pre>
<code>
No unit testing provided
</code>
</pre>

EOS-16481: Set default instance id to 1

---

ha/setup/create_pacemaker_resources.py
ha/setup/ha_setup.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-16480: Fix s3 instance dynamic and add consul

---

ha/resource/dynamic_fid_service_ra.py
ha/setup/create_pacemaker_resources.py

<pre>
<code>
EOS-17229
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Here during creating resource due to syntax error in xml
it crating issue
</code>
</pre>
<pre>
<code>
Corrected syntax and validated xml
</code>
</pre>
<pre>
<code>
It is bug fix. Tested with RPM.
</code>
</pre>

EOS-17229: Fix xml syntax error.

---

jenkins/build.sh

<pre>
<code>
setup.yaml not available in rpm
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
setup.yaml not available in rpm
</code>
</pre>
<pre>
<code>
add setup.yaml to rpm
</code>
</pre>
<pre>
<code>
No unit testing.
</code>
</pre>

Bundle setup.yaml in rpm

---

conf/etc/iem_ha.json

<pre>
<code>
Solution not given in node lost iem.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Solution not given in node lost iem.
</code>
</pre>
<pre>
<code>
Add info to check troubleshooting guide
</code>
</pre>
<pre>
<code>
No unit testing.
</code>
</pre>

EOS-17581: Update iem msg to check Troubleshooting guide

---

jenkins/rpm/v1/cortx-ha.spec
jenkins/rpm/v2/cortx-ha.spec

<pre>
<code>
Update spec for correcting licence
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
change Seagate Proprietary to Seagate
</code>
</pre>
<pre>
<code>
change Seagate Proprietary to Seagate
</code>
</pre>
<pre>
<code>
Not needed
</code>
</pre>

Update spec for Seagate Proprietary to Seagate

---

jenkins/cortx-ha.spec

<pre>
<code>
Update spec for correcting licence
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
change Seagate Proprietary to Seagate
</code>
</pre>
<pre>
<code>
change Seagate Proprietary to Seagate
</code>
</pre>
<pre>
<code>
Not needed
</code>
</pre>

Change Seagate Proprietary to Seagate

---

ha/cli/command_factory.py
ha/cli/commands.py
ha/cli/exec/clusterExecutor.py
ha/cli/exec/commandExecutor.py
ha/core/error.py

- New class for add node
- Parse command line args and validate
- Delegate the request to CLusterManger
<pre>
<code>
EOS-17929: CORTX-HA : User interface for add node CLI
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Develop CLI to add node to the cluster  </code>
</pre>
<pre>
<code>
Base framework is already there. Verify cluster add option. . If node is there. Control will go to cluster node add module and eventually to cluster manager
</code>
</pre>
<pre>
<code>
</code>
</pre>

EOS-17929: CORTX-HA : User interface for add node CLI

---

ha/core/controllers/pcs/cluster_controller.py

<pre>
<code>
https://jts.seagate.com/browse/EOS-19098
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Typo error
Typo error
</code>
</pre>
<pre>
<code>
Fix Typo
Fix Typo
</code>
</pre>
<pre>
<code>
Not needed
</code>
</pre>

EOS-19098: Typo fix

---

conf/etc/v2/alert_filter_rules.json
ha/const.py
ha/core/config/config_manager.py
ha/core/error.py
ha/core/event_analyzer/filter/filter.py
ha/setup/ha_setup.py
ha/test/integration/event_analyzer/test_alert_filter.py

Signed-off-by: Vijaykumar Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-17944 
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Implement Alerts filter which filters alerts based on the specified rules
</code>
</pre>
<pre>
<code>
Implemented alert filter as per requirement
</code>
</pre>
<pre>
<code>
Added integration test to verify alert filter
</code>
</pre>

EOS-17944 HA Event Analyzer Alerts filter code changes

---

ha/cli/exec/clusterExecutor.py

<pre>
<code>
--server should be optional
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
--server should be optional
</code>
</pre>
<pre>
<code>
--server should be optional
</code>
</pre>
<pre>
<code>
Not need
</code>
</pre>

EOS-19420: Make --server as optional

---

conf/etc/v2/cli_schema.json
ha/cli/cli_schema.py
ha/cli/command_factory.py
ha/cli/commands.py
ha/cli/cortxha.py
ha/cli/displayOutput.py
ha/cli/exec/clusterExecutor.py
ha/cli/exec/commandExecutor.py
ha/cli/exec/nodeExecutor.py
ha/cli/exec/storagesetExecutor.py
ha/const.py
ha/remote_execution/ssh_communicator.py
ha/setup/ha_setup.py
ha/test/unit/test_hw_resource.py
ha/test/unit/test_iem_resource.py

<pre>
<code>
/EOS-19435
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
/EOS-19435
</code>
</pre>
<pre>
<code>
- Provide conf/etc/v2/cli_schema.json to create help dynamically 
- command_factory.py  Remove hardcoded interface and map to usage in conf file
- change add node to add_node as add is not specific action but add_node is. And maintain cli format: cortx <module> 
- Update code to verify and return responce with value. (Pending)
<action> 
</code>
</pre>
<pre>
<code>
Not needed
</code>
</pre>

Eos 19435: Fix CLI

---

ha/setup/ha_setup.py

<pre>
<code>
EOS-19835
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
pass special char
</code>
</pre>
<pre>
<code>
added in string
</code>
</pre>
<pre>
<code>
tested on vm
</code>
</pre>

EOS-19835: Handle cluster_secret special char

---

conf/etc/rules_engine_schema_with_crossconnect.json
conf/etc/rules_engine_schema_without_crossconnect.json

<pre>
<code>
Update HA filter for new s3 DI IEMs
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
s3 will generate two new IEMs on detecting DI issues. HA needs stop IO services when processing these IEMs.
</code>
</pre>
<pre>
<code>
Updated the HA filter rules for DI IEMs, these IEMs would pass the filter with this change.
</code>
</pre>
<pre>
<code>
Tested on R1 HW setup with fake IEMs. The filter found to be working as expected.
</code>
</pre>

EOS-19336: Updated HA filter rules for DI handling

---

conf/etc/v2/cli_schema.json
ha/const.py

<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Password failed if found - at start
</code>
</pre>
<pre>
<code>
improve cli to validate
</code>
</pre>
<pre>
<code>
Tested with RPM
</code>
</pre>

EOS-20573: Improve password logic to handle -

---

conf/etc/v2/event_analyzer.service
ha/const.py
ha/core/event_analyzer/event_analyzerd.py
ha/setup/create_pacemaker_resources.py
ha/setup/ha_setup.py
jenkins/pyinstaller/v2/pyinstaller-cortx-ha.spec
jenkins/rpm/v2/cortx-ha.spec

<pre>
<code>
Story Ref (if any): EOS-17933
A daemon needs to be created for event analyzer as systemd service.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
A daemon needs to be created for event analyzer as systemd service.
</code>
</pre>
<pre>
<code>
Daemon event_analyzer_d created for event analyzer as a systemd service.
</code>
</pre>
<pre>
<code>
Installed the HA RPM on VM.
Did mini provisioner post install state
confirmed that the daemon service is seen in systemctl status 
Started the service manually, by doing "systemctl start event_analyzer.service" and confirmed that the daemon starts 
and correct code is executed
Also confirmed that logging happens correctly 
Pending tasks :
-  Currently the service is running as root . This needs to be changed to hauser;, to be …

Eos 17933 event analyzer daemon

---

ha/core/controllers/pcs/cluster_controller.py

<pre>
<code>
EOS-20796
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Cluster creation api is async so need to wait before disable stonith
</code>
</pre>
<pre>
<code>
Disable stonith if node is online
</code>
</pre>
<pre>
<code>
Tested with RPM
</code>
</pre>

EOS-20796: 1N VM-Deployment Failed in HA

---

ha/core/controllers/pcs/cluster_controller.py

Merge cortx-ha main into cortx-ha stable branch

Merge cortx-ha main into cortx-ha stable branch

---

ha/alert/alert_factory.py
ha/alert/alert_monitor.py
ha/alert/const.py
ha/alert/iem.py
ha/alert/node_alert_monitor.py
ha/alert/pcmk_alert.py
ha/alert/resource_alert_monitor.py
jenkins/pyinstaller/v2/pyinstaller-cortx-ha.spec
jenkins/rpm/v2/cortx-ha.spec

<pre>
<code>
Implement alert monitor for pacemaker alerts
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Implement alert monitor for pacemaker alerts
</code>
</pre>
<pre>
<code>
script pcmk_alert added for alert handling
class structure added for alert monitor
alert validation,  parameter parsing etc logic added to base class
Placeholder derived classes created for specific alerts
</code>
</pre>
<pre>
<code>
- Ran the file pcmk_alert.py on VM and confirmed that for the given (instrumented) config:
validations happen correctly
filters are correctly applied 
appropriate alert monitor gets called 
- Created and installed HA RPM and confirmed that the binary is generated and copied in appropriate places for pcmk_alert 
</code>
</pre>

Changes for EOS-19849 HA: Alert Generator: Implementation of alert monitor - Process_alert( )

---

ha/const.py
ha/core/event_analyzer/parser/parser.py
ha/core/system_health/const.py
ha/core/system_health/system_health_const.py
ha/test/integration/event_analyzer/test_alert_parser.py
ha/test/integration/event_analyzer/test_iem_parser.py

<pre>
<code>
EOS-19790: Implement const file for the get cluster status API. Also, override node alert type in parser.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Implement const file for the get cluster status API. Also, override node alert type in parser.
</code>
</pre>
<pre>
<code>
Added a const file to the system health module, also added code to parser for overriding the node alert type.
</code>
</pre>
<pre>
<code>
Alert and IEM parser test ran successfully.
</code>
</pre>

EOS-19790: Implemented const file and a parser fix

---

ha/alert/alert_monitor.py
ha/alert/iem.py
ha/alert/node_alert_monitor.py

<pre>
<code>
Implement node alert
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
When node alert is detected IEM creation should be called for the same 
</code>
</pre>
<pre>
<code>
create IEM called from node alert with appropriate parameters.
Actual parameter population for alert_event_module , alert_event_type will be done by EOS-18020 
</code>
</pre>
<pre>
<code>
Tested that create_iem gets called with correct parameters
</code>
</pre>

EOS-18022 CORTX-HA : Implement node alert

---

jenkins/rpm/v2/post_install_script.sh
jenkins/rpm/v2/post_uninstall_script.sh

<pre>
<code>
EOS-18360: Added provision for pcmk_alert binary.
</code>
</pre>
<pre>
<code>
Done on 1-node VM.
</code>
</pre>

EOS-18360: added pcmk_alert binary.

---

conf/etc/v2/iem_ha.json
ha/alert/iem.py

<pre>
<code>
Modify IEM description in the IEM alert
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
IEM alert was missing description line as per the document
</code>
</pre>
<pre>
<code>
Midify IEM json rule file  </code>
</pre>
<pre>
<code>
-Put Node down
- See the IEM alert in syslog
</code>
</pre>

Iem changes: Modify IEM description in the IEM alert

---

ha/alert/filter.py
ha/const.py
ha/core/cluster/cluster_manager.py
ha/core/config/config_manager.py
ha/core/controllers/element_controller_factory.py
ha/core/event_analyzer/event_analyzerd.py
ha/core/event_analyzer/filter/filter.py
ha/core/system_health/model/entity_health.py
ha/resource/alert_monitor_resource_agent.py
ha/setup/ha_setup.py
ha/test/integration/event_analyzer/test_alert_filter.py
ha/test/integration/event_analyzer/test_iem_filter.py
ha/test/integration/test_system_health.py

<pre>
<code>
Not able to change delimiter in conf
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Not able to change delimiter in conf
</code>
</pre>
<pre>
<code>
The delimiter "." replaced by ">" in Conf.get , Conf.set
Delimiter override removed from Conf.init
</code>
</pre>
<pre>
<code>
Installed the  HA RPM on VM
Ran ha_setup,  post_install, config, init and cleanup successfully  on the same 
</code>
</pre>

Changes for EOS-21143 Not able to change delimiter in conf

---

ha/setup/create_pacemaker_resources.py

<pre>
<code>
EOS-21270: Remove unnecessary constraints.
</code>
</pre>
<pre>
<code>
Tested on 3-node VM.
</code>
</pre>

EOS-21270: Removed unneccessary constraints.

---

ha/alert/const.py
ha/alert/filter.py

<pre>
<code>
Issue found in delimiter in alert/filter.py
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
delimiter incorrect in  ha/alert/filter.py
</code>
</pre>
<pre>
<code>
Fixed the delimiter issue alert/filter.py
</code>
</pre>
<pre>
<code>
Verified on deployment that the change is correct 
</code>
</pre>

Changes for EOS-21143 Not able to change delimiter in conf (#466)

---

ha/const.py
ha/setup/post_disruptive_upgrade.py
ha/setup/pre_disruptive_upgrade.py

<pre>
<code>
EOS-20986
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- Resource list logic have few issue
- Exit status is not correct when failed
- Pre check and post check for script missing
</code>
</pre>
<pre>
<code>
Update code
</code>
</pre>
<pre>
<code>
Tested with rpm
</code>
</pre>

EOS-20986: Update pre disruptive upgrade fix

---

ha/setup/ha_setup.py
ha/setup/post_disruptive_upgrade.py

<pre>
<code>
See commit msg.  </code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
See commit msg.  </code>
</pre>
<pre>
<code>
See commit msg.  </code>
</pre>
<pre>
<code>
No  </code>
</pre>

EOS-22007: post-disruptive upgrade fix and minor HA mini-provisioner refactoring

---

conf/etc/v2/ha.conf.template
conf/mini_provisioner/v2/ha.config.tmpl.1-node
conf/mini_provisioner/v2/ha.config.tmpl.3-node
conf/mini_provisioner/v2/ha.init.tmpl.1-node
conf/mini_provisioner/v2/ha.init.tmpl.3-node
ha/setup/ha_setup.py

<pre>
<code>
EOS-20798: Create as many io services as cvg_count present in conf store.
</code>
</pre>
<pre>
<code>
Yes on 3-node VM.
</code>
</pre>

EOS-20798: create ios service instances based on cvg_count.

---

ha/core/controllers/pcs/cluster_status.py

<pre>
<code>
See commit message.
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Hotfix for cluster_status modure: _get_confstore -> get_confstore

---

ha/setup/ha_setup.py

Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>
<pre>
<code>
See commit message.
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>

Hotfix: add missing delimiter to post disruptive upgrade hook

---

ha/setup/ha_setup.py
ha/setup/pcs_config/alert_config.py

<pre>
<code>
EOS-22080
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Early alert creation misleading node add message
</code>
</pre>
<pre>
<code>
Move alert creation to last step of config
</code>
</pre>
<pre>
<code>
Tested with RPM
</code>
</pre>

EOS-22080: Fix alert creation

---

ha/setup/ha_setup.py
ha/test/integration/event_analyzer/test_iem_parser.py
ha/test/integration/test_consul_kv.py
ha/util/consul_kv_store.py

<pre>
<code>
EOS-22934
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
All data not cleaned up
</code>
</pre>
<pre>
<code>
Your Problem solution here..
Clean all consul keys
</code>
</pre>
<pre>
<code>
- Checked cleanup with run in parallel on all node
- Cleanup with --local to check confstore.delete is working for deleting single key
</code>
</pre>

EOS-22934: Cleanup consul data

---

ha/core/controllers/pcs/node_controller.py
ha/core/controllers/pcs/pcs_controller.py

<pre>
<code>
Change input parameter pvtfqdn to node_id
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Previously we are considering nodeid as pvfqdn (node_name). we need to change it to nodeid.
</code>
</pre>
<pre>
<code>
Changed input parameter from pvtfqdn to nodeid
</code>
</pre>
<pre>
<code>
</code>
</pre>

Changed input parameter pvtfqdn to node_id

---

ha/core/event_manager/resources.py
ha/core/system_health/model/entity_health.py
ha/core/system_health/system_health.py
ha/util/enum_list.py

<pre>
<code>
EOS-23218
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Do not overwrite node status to failed if offline already
</code>
</pre>
<pre>
<code>
Implement code
</code>
</pre>
<pre>
<code>
Tested on system
- Previous message offline new message send is failed and health is not updated that time
</code>
</pre>

EOS-23218: Fix system health node update

---

ha/core/event_analyzer/watcher/watcher.py
ha/test/test_message_bus_wrapper.py
ha/util/message_bus.py
jenkins/dev_env/README.md
jenkins/dev_env/build_prerequisite.sh
jenkins/dev_env/build_rpm.sh
jenkins/dev_env/conf/example_config_hw.json
jenkins/dev_env/conf/example_config_multinode.json
jenkins/dev_env/conf/example_config_singlenode.json
jenkins/dev_env/cortx_configure.sh

<pre>
<code>
Message bus is not centralized 
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Provide centralized message bus
</code>
</pre>
<pre>
<code>
Provide centralized message bus
</code>
</pre>
<pre>
<code>
Provide test case
</code>
</pre>

EOS-22209: Message Bus code

---

ha/core/system_health/system_health.py

<pre>
<code>
EOS-23593
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
None type alert getting first time
</code>
</pre>
<pre>
<code>
Handle case
</code>
</pre>
<pre>
<code>
Done setup
post_install
Mini Provisioning post_install configured successfully.
prepare
Mini Provisioning prepare configured successfully.
config
Mini Provisioning config configured successfully.
init
Mini Provisioning init configured successfully.
Checked pcs status and health status
</code>
</pre>

EOS-23593: Fix health update

---

ha/core/config/config_manager.py
ha/core/system_health/system_health.py

<pre>
<code>
change nodeid tp node name
</code>
</pre>
<pre>
<code>
yes
</code>
</pre>
<pre>
<code>
node id to node name  
</code>
</pre>
<pre>
<code>
node id to node name  
</code>
</pre>
<pre>
<code>
/usr/bin/python3 /home/708945/src/Repos/cortx-ha/ha/core/system_health/system_health.py
srvnode-2
</code>
</pre>

EOS-17967: Node id fix

---

ha/core/health_monitor/health_monitord.py
ha/util/message_bus.py

<pre>
<code>
Updated code to undle exception
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Exception creating loop
</code>
</pre>
<pre>
<code>
Handle exception properly
</code>
</pre>
<pre>
<code>
Tested in hare ha integration
</code>
</pre>

EOS-17967: Fix message bus

---

ha/core/health_monitor/health_monitord.py
ha/test/integration/health_monitor/test_publisher.py

<pre>
<code>
Fix codacy issue for an unused import and message bus instantiation
</code>
</pre>
<pre>
<code>
Yes, tested using the workspace.
</code>
</pre>
<pre>
<code>
Fix codacy issue for an unused import and message bus instantiation
</code>
</pre>
<pre>
<code>
Removed unused import and fixed message bus instantiation in the test file
</code>
</pre>
<pre>
<code>
test_publisher.py ran successfully with these changes.
</code>
</pre>

EOS-22209: Removed unused 'HealthMonitorError' import

---

ha/resource/service_instances_counter.py
ha/resource/vip_health_monitor.py
ha/setup/const.py
ha/setup/create_pacemaker_resources.py
jenkins/rpm/v2/post_install_script.sh
jenkins/rpm/v2/post_uninstall_script.sh

<pre>
<code>
vip is making eth up and not getting failure
EOS-23313
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
vip is making eth up and not getting failure
</code>
</pre>
<pre>
<code>
Add dependency
</code>
</pre>
<pre>
<code>
Tested on vm
1. tested by ifdown eth0
2. tested by ip link set down eth0
In both case seen that resource are getting failover to other node
</code>
</pre>

EOS-23313: Create vip health check

---

conf/etc/v2/ha.conf.template

EOS-19206: Fixed the merge conflict resolution issue

EOS-19206: Fixed the merge conflict resolution issue

---

.github/workflows/alex_reviewdog.yml
VERSION
conf/etc/v2/actuator_req.json
conf/etc/v2/ha.conf.template
ha/const.py
ha/core/cluster/cluster_manager.py
ha/core/config/config_manager.py
ha/core/controllers/node_controller.py
ha/core/controllers/pcs/cluster_controller.py
ha/core/controllers/pcs/node_controller.py
ha/core/controllers/pcs/pcs_controller.py
ha/core/controllers/pcs/service_controller.py
ha/core/controllers/service_controller.py
ha/core/system_health/const.py
ha/core/system_health/model/entity_health.py
ha/core/system_health/system_health.py
ha/resource/service_instances_counter.py
ha/resource/vip_health_monitor.py
ha/setup/const.py
ha/setup/create_pacemaker_resources.py
ha/setup/ha_setup.py
ha/test/integration/test_actuator_req_resp.py
ha/util/actuator_req_manager.py
ha/util/fencing_agent.py
ha/util/ipmi_fencing_agent.py
ha/util/machine_id.py
ha/util/message_bus.py
jenkins/rpm/v2/post_install_script.sh
jenkins/rpm/v2/post_uninstall_script.sh

Merge cortx-ha main into stable

Merge cortx-ha main into stable

---

.github/auto_assign.yml

Auto assign members list updated for HA

Auto assign members list updated for HA

---

.github/stale.yml

Members updated in community support list

Members updated in community support list

---

.github/pull_request_template.md

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
-----
[View rendered .github/pull_request_template.md](https://github.com/gauravchaudhari02/cortx-ha/blob/add-template/.github/pull_request_template.md)

Adhoc : Update PR template

---

.github/auto_assign.yml
.github/stale.yml
CODEOWNERS

- Change in Codeowners & Auto assign reviewers

Change in Codeowners & Auto assign reviewers

---

whitesource.config

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
- Problem statement
Adding exclude parameter to whitesource configuration
- 
Please note, I am not creating any new defect for this change. Instead I am referring to PyYAML upgrade defect to fix it.
https://jts.seagate.com/browse/EOS-23696
Testing will be conducted as part of PR scan
- [] Is perfline test run and the report with and without the changes updated in the PR? [Y/N]: - No
Not applicable

EOS-23696 - Update whitesource configuration

---

ha/const.py
ha/core/error.py
ha/core/event_analyzer/event_analyzerd.py
ha/core/event_analyzer/parser/parser.py
ha/core/health_monitor/health_monitord.py
ha/core/system_health/system_health.py
ha/fault_tolerance/cluster_stop_monitor.py
ha/fault_tolerance/fault_monitor.py
ha/fault_tolerance/fault_tolerance_driver.py
ha/k8s_setup/const.py
ha/k8s_setup/ha_setup.py
ha/monitor/k8s/const.py
ha/monitor/k8s/monitor.py
ha/monitor/k8s/object_monitor.py
ha/test/integration/test_sigterm_to_ha_services.py
ha/util/conf_store.py
ha/util/message_bus.py

fault_k8s to main merge
fault_k8s to main  branch merge
-  [ ] Coding conventions are followed and code is consistent : NA
NA : fault_k8s to main merge
NA:  fault_k8s to main merge

fault_k8s to main merge

---

ha/const.py
ha/core/event_analyzer/event_analyzerd.py
ha/core/event_analyzer/parser/parser.py
ha/core/system_health/system_health.py
ha/core/system_health/system_health_manager.py
ha/fault_tolerance/cluster_stop_monitor.py
ha/fault_tolerance/fault_monitor.py
ha/k8s_setup/ha_setup.py
ha/k8s_setup/ha_start.py
ha/monitor/k8s/object_monitor.py
ha/test/integration/test_sigterm_to_ha_services.py

fault_k8s -> main merge
fault_k8s -> main merge
NA
NA
NA
fault_k8s -> main merge

Fault k8s ->main merge

---

.github/auto_assign.yml
CODEOWNERS

Added code owner for HA as per EOS-27319

EOS-27319: Added code owner for HA

---

ha/fault_tolerance/cluster_stop_monitor.py
ha/test/integration/test_sigterm_to_ha_services.py

fault_k8s to main merge coveing EOS-27939 Integration issue for message 'start_cluster_shutdown' ...
NA: branch to branch merge 
NA: branch to branch merge 
NA: branch to branch merge 
NA: branch to branch merge 
NA: branch to branch merge 
NA: branch to branch merge

EOS-27939 : fault_k8s to main merge

---

conf/etc/v2/system_health_hierarchy.json
ha/const.py
ha/core/event_manager/resources.py
ha/core/system_health/const.py
ha/core/system_health/status_mapper.py
ha/core/system_health/system_health_metadata.py

- System health schema needs to be expanded to include resources : cvg , disk and the additional states possible for these resources
-  Added cvg , disk as new resources in the system health schema and in constants
- Added recovering, recovered, rebalancing as new states
Test details added as comment 

CORTX-27962 System health schema expansion to include storage and storage nodes to include CVG and underlying disk devices

---

ha/fault_tolerance/const.py
ha/fault_tolerance/event.py

- Add const.py file under fault_tolerance directory with the content as mentioned in the LLD.
Add "Health Status Event Message Schema" with the default values populated as mentioned in the LLD
https://jts.seagate.com/browse/CORTX-27956
Create Event Message Schema Class with initialize default value.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD?focusedCommentId=909705441#Health-Status-Event-Message-Schema
Event object __dict__ : 
{'event': {'header': {'version': '1.0', 'timestamp': '1645446906', 'event_id': '16454469064844cfc1ff3f451ca36de8fa1c4385a7'}, 'payload': {'source': None, 'cluster_id': None, 'site_id': None, 'rack_id': None, 'storageset_id': None, 'node_id': None, …

Cortx 27956 new: Implement action event interface

---

ha/core/action_handler/action_factory.py
ha/core/action_handler/action_handler.py
ha/k8s_setup/const.py
ha/k8s_setup/ha_setup.py

Handling needs to be added to Subscribe for disk events from Hare and to send disk alerts to Hare
Changes added for
Hare subscription for resource type disk in HA mini provisioning
Action Handlers added for disk and cvg resource types
LLD at https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD
https://jts.seagate.com/secure/attachment/506958/testing_details_CORTX-28605.txt

CORTX-28605 Subscribe to disk events and changes to ActionHandler to send disk alerts to Hare

---

ha/const.py
ha/core/event_analyzer/parser/parser.py
ha/core/event_manager/const.py
ha/core/event_manager/event_manager.py
ha/core/health_monitor/monitor_rules_manager.py
ha/core/system_health/health_evaluators/element_health_evaluator.py
ha/core/system_health/system_health.py
ha/core/system_health/system_health_metadata.py
ha/fault_tolerance/const.py
ha/k8s_setup/const.py
ha/k8s_setup/ha_setup.py
ha/monitor/k8s/parser.py
ha/test/integration/test_consul_kv.py
ha/test/integration/test_hw_resource.py
ha/util/conf_store.py
ha/util/consul_kv_store.py
ha/util/health_generator/README.md

fault_k8s to main merge PR 
fault_k8s to main merge PR 
-  [] Coding conventions are followed and code is consistent
NA 
NA
NA
NA
NA
-----
[View rendered ha/util/health_generator/README.md](https://github.com/Seagate/cortx-ha/blob/fault_k8s/ha/util/health_generator/README.md)

CORTX-29079  fault_k8s to main merge PR 

---

ha/const.py
ha/core/action_handler/action_handler.py
ha/core/health_monitor/health_monitord.py
ha/core/system_health/status_mapper.py
ha/core/system_health/system_health.py
ha/fault_tolerance/fault_tolerance_driver.py
ha/util/conf_store.py

Update storage resources(CVG, Disk) health status in System Health
- Problem statement
https://jts.seagate.com/browse/CORTX-27991
LLD: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD
https://jts.seagate.com/secure/attachment/509955/cvg_test.txt
https://jts.seagate.com/secure/attachment/509956/disk_test.txt

CORTX-27991: Update storage resources(CVG, Disk) health status in System Health

---

ha/const.py
ha/core/action_handler/action_handler.py
ha/core/system_health/const.py
ha/core/system_health/status_mapper.py
ha/core/system_health/system_health.py
ha/core/system_health/system_health_metadata.py
ha/fault_tolerance/fault_tolerance_driver.py
ha/k8s_setup/ha_setup.py
ha/test/integration/health_monitor/test_event_action_handler.py
ha/test/integration/health_monitor/test_k8s_publisher.py
ha/test/integration/health_monitor/test_publisher.py
ha/util/conf_store.py

PR to merge fault_k8s into main branch
Merge contains F-27, F-24 and other changes 
NA
NA
NA
NA
NA

CORTX-29079 fault_k8s to main merge

---

ha/const.py
ha/core/system_health/system_health.py
ha/core/system_health/system_health_manager.py
ha/fault_tolerance/fault_tolerance_driver.py
ha/k8s_setup/ha_start.py
ha/test/main.py
ha/util/conf_store.py
ha/util/consul_kv_store.py

- PR to merge fault_k8s into main branch
- PR to merge fault_k8s into main branch
NA : PR to merge fault_k8s into main branch
NA : PR to merge fault_k8s into main branch
NA : PR to merge fault_k8s into main branch
NA : PR to merge fault_k8s into main branch
NA : PR to merge fault_k8s into main branch

CORTX-29079 fault k8s to main merge

---

ha/k8s_setup/const.py
ha/util/conf_store.py

Add control node cluster cardinality and watch control node events
[CORTX-29930](https://jts.seagate.com/browse/CORTX-29930) - Enhance monitoring capability for control node
[test_results.txt](https://jts.seagate.com/secure/attachment/513113/test_results.txt)

CORTX-29930: Enhance monitoring capability for control node

---

ha/k8s_setup/ha_setup.py

…hancement
- HA needs to act on the events received from HARE for cluster state change based
on the defined algorithm. This state needs to be added in the system health for the
cluster key. So, once that alert is received by fault_monitor, this needs to be passed
from event analyzer filter and parser. Filter will pass it based on the alert resource
type. Currently, filter list has node, disk, cvg as resource type. So, this list needs
to be modified for "cluster" resource type as well.
- https://jts.seagate.com/browse/CORTX-30030
HA should accept cluster state change alert from HARE and HA Event Analyzer should able to filter and parse it to system health for further processing.
HA resource type Event Analyzer filter list needs to be …

CORTX-30030: cluster status: Event analyzer filter and parse logic enhancement

---

ha/util/health_generator/mock_health_event_publisher.py

Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Invalid argument validations are not properly handled.
-  Added validation to check for Invalid Argument
https://jts.seagate.com/secure/attachment/514154/test_results_29708.txt

CORTX-29708: Add proper validation of args in mock_health_event_publisher.py file

---

ha/util/health_generator/mock_health_event_publisher.py

- After current implementation, some end case scenarios (i.e for handlers like publish, get-disks etc) were not properly handled.
- Updated the list of arguments to validate.
https://jts.seagate.com/secure/attachment/514444/test_results_29708.txt

Cortx 29708: Handle validations for all the arguments and handlers in mock_health_event_publisher.py file.

---

ha/k8s_setup/ha_setup.py

- Cluster status gets updated in system health 
- Cluster status gets updated in system health 
Testing details are in https://jts.seagate.com/secure/attachment/515400/test_results.txt

CORTX-30050 cluster status: system health updates

---

ha/core/system_health/system_health.py

Signed-off-by: gauri-bhosale <gauri.bhosale@seagate.com>
-https://jts.seagate.com/browse/CORTX-29987
- system_health should pick functional_type from current_health
- https://jts.seagate.com/secure/attachment/516084/Test_Results.txt
-
-https://jts.seagate.com/secure/attachment/516084/Test_Results.txt

CORTX-29987: System health update for control node: existing functionality is unchanged

---

ha/core/event_manager/subscribe_event.py
ha/k8s_setup/ha_setup.py
ha/util/conf_store.py

Optimizing ha_setup to reduce consul accesses
Optimizing ha_setup to reduce consul accesses

Cortx 29667  Optimizing ha_setup to reduce consul accesses

---

CODEOWNERS

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Changed Code owners for HA component

CORTX-31210: Changed Code owners

---

ha/k8s_setup/const.py
ha/k8s_setup/ha_setup.py
ha/monitor/k8s/const.py
ha/monitor/k8s/monitor.py
ha/monitor/k8s/object_monitor.py
ha/monitor/k8s/parser.py
ha/util/conf_store.py

- This is integration branch for 2 tasks
- Tasks CORTX-31528 and CORTX-21529
- both are reviewed separately in the below links and combined here for testing and merging into main brach
- https://github.com/Seagate/cortx-ha/pull/714
- https://github.com/Seagate/cortx-ha/pull/715
-  for more information please refer to the below links
- https://github.com/Seagate/cortx-ha/pull/714
- https://github.com/Seagate/cortx-ha/pull/715
- [] Unit and System Tests are added.
Test log file link: https://jts.seagate.com/secure/attachment/520280/CORTX-31528-2.log

Cortx 31528 integration

---

ha/k8s_setup/const.py
ha/util/message_bus.py

HA POD deployment is facing problems and getting timed out. The probable cause is unable to connect to Kafka.
Solution:
Implementing retries to connect to Kafka will help and will avoid timed out
issue while deployment
https://jts.seagate.com/browse/CORTX-31665
https://jts.seagate.com/secure/attachment/534139/CORTX-31665_test_details.txt

CORTX-31665: HA Pod occasionally hangs while running cortx-setup initContainer
