Seagate/cortx-ha

conf/script/build-ees-ha-update
`build-ees-ha-update` tries to execute Bash builtin command directly.
```
$ sudo export PATH=$PATH:/usr/bin
sudo: export: command not found
```
Solution: remove unneeded `sudo`.
Jira: [EOS-12635](https://jts.seagate.com/browse/EOS-12635)
=> Problem: build-ees-ha-update fails

conf/etc/consul_watcher_failback.json, conf/etc/ha.conf, conf/script/ha_setup, ha/cli/command_factory.py, ha/cli/commands.py, ha/cli/cortxha.py, ha/const.py, ha/core/cluster/cluster_manager.py, ha/core/error.py, ha/core/node/replacement/refresh_context.py, ha/execute.py, ha/resource/resource_agent.py, jenkins/cicd/cortx-ha-cicd.sh, jenkins/cicd/etc/ha.conf
- Added CLI
- Added error logic
- Added Cluster managment
- Added Cleanup
<pre>
<code>
EOS-11314 | HA: Provide program to trigger failback and handle action
Provide failback support for HA
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
After fault resolved cluster should go to normal state.
</code>
</pre>
<pre>
<code>
Detect alert and provide cleanup from consul watcher
</code>
</pre>
<pre>
<code>
Testing done with sas fault and resolved:
io_path failed after sas fault and after reolve cluster moved to normal state
log
2020-09-25 05:22:26 cortxha INFO [reset_failover] Resource failcount before Failback: Failcounts for resource 'io_path_health-c1'
srvnode-1: INFINITY
, Error:, RC:0
2020-09-25 …
=> failback: Add support for failback

conf/script/build-cortx-ha, conf/script/build-ha-io
Currently, /var/motr is mounted before hax service startup and
unmounted after hax service stop. This mounting/unmounting is done
in hax systemd service unit file. So when hax fails to stop within
30 secs timeout (configured in Pacemaker), the node will be fenced
by Pacemaker to avoid the situation when /var/motr is mounted on
both nodes at the same time (which would lead to data corruption).
Hax stopping can be delayed for different reasons, mainly due to
bugs in Motr which are not easy to fix quickly (for example, hax
calls rconfc_start in fs-stats thread and it may get stuck if confd
process dies and does not come up during the node shutdown). So
we are solving it from another side:
1) Create separate resource in Pacemaker for /var/motr mgmt and
stop doing it from hax systemd unit …
=> EOS-13393: fix nodes fencing issue on sporadic hax stop timeouts (#144)

conf/script/build-ha-io, ha/resource/lnet
Currently, the build-ha-io script expects that the name of the
data network interface is the same on both nodes, which sometimes
may not be the case when the underlying HW is different. (Which
may happen, for example, when the old failed node is replaced
with the new one.)
Solution: add support for different interface names via the
two new configuration options: `--left-iface` and `--right-iface`.
If the options are not explicitly set by user, the value of
the old `--iface` option is used for both interfaces.
Closes EOS-13356.
Reviewed-by: Ajay Srivastava <ajay.srivastava@seagate.com>
Reviewed-by: Mandar Sawant <mandar.sawant@seagate.com>
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
(cherry picked from commit e185aa25323413b6f134c7ab184dd32485971e8d)
=> build-ha-io: support different interfaces on the nodes (#145)

conf/script/build-ha-io
The patch for "support different interfaces on the nodes"
introduced the regression in CDF update code, so that interface
names would become like "enp179s0f1:enp179s0f1" instead of
"enp179s0f1:c1" or "enp179s0f1:c2".
Solution: fix the code in the sed expression.
Kudos to Madhav Vemuri for excellent initial investigation.
Reviewed-by: Madhav Vemuri <madhav.vemuri@seagate.com>
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
=> EOS-13695: build-ha-io: fix regression in CDF update code

conf/script/build-ha-io
The parameter names should be with a hyphen (not underscore),
similar to all the rest parameters names and aligned with the doc.
=> build-ha-io: fix left/right interface parameters names

conf/script/build-ha-io
The patch for "support different interfaces on the nodes"
introduced the regression in CDF update code, so that interface
names would become like "enp179s0f1:enp179s0f1" instead of
"enp179s0f1:c1" or "enp179s0f1:c2".
Solution: fix the code in the sed expression.
Kudos to Madhav Vemuri for excellent initial investigation.
Reviewed-by: Madhav Vemuri <madhav.vemuri@seagate.com>
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
(cherry picked from commit 41783b704ea05957425a2038e08fa364b806fb55)
=> EOS-13695: build-ha-io: fix regression in CDF update code (#160)

conf/script/build-ha-io
The parameter names should be with a hyphen (not underscore),
similar to all the rest parameters names and aligned with the doc.
Reviewed-by: Yashodhan Pise <yashodhan.pise@seagate.com>
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
Co-authored-by: indrajitzagade <63033334+indrajitzagade@users.noreply.github.com>
(cherry picked from commit df8eed2160416304ea6bb85fdb0dd92ef597a6a5)
=> build-ha-io: fix left/right interface parameters names (#159)

conf/script/build-ha-io
<pre>
<code>
prepare_var_motr_dirs() may fail thus exiting the script
</code>
</pre>
<pre>
<code>
Yes, directly on hardware system
</code>
</pre>
<pre>
<code>
prepare_var_motr_dirs() checks on both the nodes if /var/motr1 and
/var/motr2 dirs are present, if not then renames the /var/motr to
/var/motr1 or /var/motr2 on respecive nodes.
While executing this command on the peer node the check condition
may fail if directories already exist thus leads to failure of the
ssh command for the peer node. This leads to script exit as `pipefail`
is set for the script.
</code>
</pre>
<pre>
<code>
Make the directory creation command no-op by returning true in case of
check condition failure to continue the build script.
</code>
</pre>
<pre>
<code>
build-ha-io script must succeed
</code>
</pre>
=> Problem: prepare_var_motr_dirs() may fail thus exiting the script

conf/script/build-ha-io
<pre>
<code>
Problem: wrong /var/motr links created if restore executed from secondary node
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
prepare_var_motr_dirs() is also executed to restore /var/motr directories
post node replacement. But the function presently assumes it to be executed
from primary node only which may not be the case during restore as restore
can be executed from secondary node as well. This creates wrong /var/motr
links.
</code>
</pre>
<pre>
<code>
Run /var/motr creation commands over ssh for both the nodes to handle the
execution from any of the nodes.
</code>
</pre>
<pre>
<code>
None
</code>
</pre>
=> Problem: wrong /var/motr links created if restore executed from secondary node

conf/script/build-ha-io
Currently, the commands which check for /var/motr dir present
at prepare_var_motr_dirs() (and run some upgrade logic if it
is) do not tolerate the situation when /var/motr directory
is not present - they would return non-zero status (thus,
failing the whole script which is wrong).
Solution: fix the commands by appending `|| true` to them.
Kudos to Mandar Sawant who caught this.
=> build-ha-io: fix bogus failure of prepare_var_motr_dirs()

conf/script/prov-m0-reset
<pre>
<code>
prov-m0-reset --mkfs-only does not provide option to run on both nodes
</code>
</pre>
<pre>
<code>
Tested on hardware setup as part of data recovery.
</code>
</pre>
<pre>
<code>
Due to lvm used for Motr meta data segments running mkfs on the volumes on
single node does not reflect the changes on peer node when data recovery is
executed on both the nodes in parallel. Presently prov-m0-reset --mkfs-only
execution does not provide to run the operation on both the nodes.
</code>
</pre>
<pre>
<code>
Provide and option for the user to run m0mkfs for both the nodes on single node
or on individual nodes.
</code>
</pre>
<pre>
<code>
Run data recovery.
</code>
</pre>
=> Problem: prov-m0-reset --mkfs-only does not provide option to run on both nodes

conf/script/prov-m0-reset
<pre>
<code>
cob domain is unavailable even after motr ios is started
</code>
</pre>
<pre>
<code>
Yes, on hardware system.
</code>
</pre>
<pre>
<code>
After motr-mkfs, motr ioservices are needed to be started to facilitate cob
domain creation which is not created as part of mkfs operation.
But still cob domain is not available even after motr ioservice reported
M0_CONF_HA_PROCESS_STARTED.
</code>
</pre>
<pre>
<code>
- Wait for sometime (15 secs) before stopping motr ioservices to allow
some time for cob domain creation.
- Fix typo and invoke cleanup before checking for consul service at mkfs
start.
Note: Created https://jts.seagate.com/browse/EOS-13779 to remove this
workaround once https://jts.seagate.com/browse/EOS-13778 is fixed.
</code>
</pre>
<pre>
<code>
Tested on hardware, script …
=> Problem: cob domain is unavailable even after motr ios is started

ha/const.py, ha/core/cluster/cluster_manager.py
- Node retiries logic added
<pre>
<code>
https://jts.seagate.com/browse/EOS-13826
add_node failing
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
For add_node
/opt/seagate/cortx/ha/conf/script/cluster_update add_node
it is executed properly and node added to cluster
but from log
as it was async with pcs
`opt/seagate/cortx/ha/conf/script/cluster_update add_node`
not able to find node online but node part of cluster
it may happen if node goes to unclean or standby or rebooted or pcs take time to add node to cluster
</code>
</pre>
<pre>
<code>
Add retry to check if node added to cluster
if node online return good but if node added to cluster and not online then add it in log
if still node not …
=> add_node_fix: Fix add node to cluster

ha/resource/sspl
In master mode, when sspl resource is not running, the resulting
code of monitor command returned by sspl resource agent would be
OCF_ERR_GENERIC which is wrong. Upon receiving such a code
Pacemaker would not try to restart the resource.
Solution: return OCF_NOT_RUNNING code instead.
To facilitate debugging, we add logging into the syslog also,
as a bonus.
Tested manually on the setup while debugging the problem
about SSPL promotion failure.
=> sspl-ra: fix monitor result in master mode

ha/resource/resource_agent.py
<pre>
<code>
Improve M4 resource time
https://jts.seagate.com/browse/EOS-13330
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
During node crash there is sleep time and while loop. When pacemaker calling sleep time as there some monitor call remaining pacemaker waiting more like upto 23 sec to complete stop call.
</code>
</pre>
<pre>
<code>
Remove unwanted code as not required.
</code>
</pre>
<pre>
<code>
Integration testing done unit testing not provided
</code>
</pre>
=> Time improve

conf/script/build-ha-io
<pre>
<code>
ClusterIP resource may sporadically fail and migrate to another node
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Empty.
</code>
</pre>
<pre>
<code>
Since the reason is unknown so far, this patch is supposed to mitigate
the problem making pacemaker to retry ClusterIP resource on banned node
once in 5 minutes.
Nothing depends from ClusterIP resource, so it is not supposed to cause
restart of other resources.
Timeout value is chosen in order to not disturb cluster too frequently.
The consequences of suggested patch are:
* Once in 5 minutes ClusterIP failures will be cleaned from 'pcs status'
log. However they persist in syslog and corosync log.
In case resource is not recovered successfully 'pcs status' will
continue to show failed status soon.
</code>
</pre> …
=> Problem: ClusterIP resource may sporadically fail and migrate to another node

conf/script/prov-m0-reset
<pre>
<code>
--single-node option to prov-m0-reset fails
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
As part of the implementation to support single as well as dual node mkfs,
singlenode option implementation got missed to be updated to not expect any
value as part of the final version of the script.
</code>
</pre>
<pre>
<code>
Fix --single-node option to the prov-m0-reset script to not expect any value.
</code>
</pre>
<pre>
<code>
prov-m0-reset must run for single node with --single-node option.
</code>
</pre>
=> Problem: --single-node option fails

conf/script/prov-m0-reset
<pre>
<code>
hax service start fails in absence of /var/motr/hax
</code>
</pre>
<pre>
<code>
Yes, tested on the hardware with local changes and confirmed by data recovery team.
</code>
</pre>
<pre>
<code>
In case /var/motr is wiped off clean during data recovery then hare-hax
service fails to start due to absence of /var/motr/hax directory.
</code>
</pre>
<pre>
<code>
Create /var/motr/hax directories if it does not exists on respective /var/motr
volumes before starting hare-hax services as part of mkfs operation.
</code>
</pre>
<pre>
<code>
prov-m0-reset --mkfs-only must complete successfully with a clean /var/motr directory.
</code>
</pre>
=> Problem: hax service start fails in absence of /var/motr/hax

conf/script/build-ha-io
<pre>
<code>
S3 requests will fail if haproxy on a node dies and clusterIP is running.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
In following case when
* ClusterIP is running
* Other services are running except HAProxy.
* HAProxy goes down because of some reason and it has reached max failure count.
The ClusterIP will still route S3 request to this node, which will cause requests to fail.
</code>
</pre>
<pre>
<code>
Collocate ClusterIP with haproxy service.
</code>
</pre>
<pre>
<code>
Checked rpmbuild and bash code correctness.
</code>
</pre>
=> EOS-14162: collocate ClusterIP with haproxy

conf/script/build-ha-io
This reverts commit 321e0d94eceb4d4f4e66594444d0ad808a48680d.
Revert is caused by regression documented in EOS-15004 and EOS-14827:
haproxy-running attribute dependency between ClusterIP and haproxy
resources caused deadlock because haproxy can't start without running
ClusterIP.
Signed-off-by: Andrei Zheregelia <andrei.zheregelia@seagate.com>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
=> EOS-14827: Revert "EOS-14162: collocate ClusterIP with haproxy (#237)"

conf/script/build-ha-csm
Failback was not successful since pacemaker remember last attempt
to start resource which was failed. It required to set failure-timeout
for resource. Pacemaker will able to attempt starting of failed
resource after failure-timeout.
Solution:
Add failure-timeout for csm_web.
Ref: EOS-15013
=> Problem: Failback not happens for csm_web since failure-timeout not set

ha/resource/sspl
<pre>
<code>
Error was reported in update from build 454->463 using csm cli
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
SW update failed at components.ha.iostack-ha.post_update  from build 454->463 using csm cli
</code>
</pre>
<pre>
<code>
syntax error found in sspl resource promote and demote is fixed
</code>
</pre>
<pre>
<code>
-
</code>
</pre>
=> Eos 15127 SW update failed at components.ha.iostack-ha.post_update

conf/script/build-ha-csm
<pre>
<code>
cidr_netmask parameter is hardcoded for kibana-vip resource 
https://jts.seagate.com/browse/EOS-15043
</code>
</pre>
<pre>
<code>
No. 
</code>
</pre>
<pre>
<code>
Provisioner component is missing the capability to specify netmask that shall be set on kibana-vip IP created in build-ha-csm script. This causes EOS-15043 bug where netmask is set incorrectly.
</code>
</pre>
<pre>
<code>
Add cidr parameter for build-ha-csm script  
</code>
</pre>
<pre>
<code>
Script is launched on local setup.
</code>
</pre>
=> EOS-15043: Make cidr_netmask parameter configurable for kibana-vip resource

conf/script/build-ha-io
<pre>
<code>
https://jts.seagate.com/browse/EOS-15165
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
haproxy depends on ClusterIP resource because it has bind requirement in
configuration.
During cluster update it happens that haproxy starts when ClusterIP is
being restarted. So haproxy fails immediately (on both nodes) and nodes
became banned.
</code>
</pre>
<pre>
<code>
Solution: add retry feature to haproxy-c1/2 resource (failure-timeout=60s)
This won't fix an issue but mitigates it making haproxy to restart when
ClusterIP is present
Notes: we may want to consider ordering constraint as well to implement
following ordering:
ClusterIP-clone |
s3servers-c1/2  | -> haproxy
So, restart/stop of ClusterIP-clone will cause haproxy restart/stop.
This approach requires some testing …
=> EOS-15165: Add failure timeout to haproxy

conf/script/build-ha-csm, conf/script/build-ha-sspl
<pre>
<code>
build-ha-csm fails to complete build-ha-csm-args.yaml file
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
build-ha-csm uses IFS (bash internal field separator) set to `:` to read build-ha-csm-args.yaml
file. The build-ha-csm-args.yaml file is read iteratively in while loop using read command, the
read may fail if the line does not end with a newline character. This is what happens while reading
build-ha-csm-args.yaml by build-ha-csm script. The last line not ending with a newline character
is skipped and required data remains unread leading to failure of the build-ha-csm script.
</code>
</pre>
<pre>
<code>
- Use regEx along with the IFS to handle such situations.
- Handle extra spaces and blank lines in the args file as well.
- Fix build-ha-sspl script as well to …
=> EOS-15282: build-ha-csm fails to complete build-ha-csm-args.yaml file

conf/script/build-ha-update
Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-15329: Build 515: Unsuccessful update to build 529 after primary node replacement
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Observed build-ha-update script took more time to delete and recreate resources.
</code>
</pre>
<pre>
<code>
Did changes to move cluster into standby mode before deleting resources and moving back to unstandby mode after recreating resources again.
</code>
</pre>
<pre>
<code>
</code>
</pre>
=> EOS-15329: Move cluster into standby mode before deleting the resources 

ha/pcswrap/pcswrap/client.py, ha/pcswrap/pcswrap/internal/connector.py, ha/pcswrap/pcswrap/types.py, ha/pcswrap/tests/status-long-21.xml, ha/pcswrap/tests/status-long-23.xml, ha/pcswrap/tests/status-xml-plain-resources.xml, ha/pcswrap/tests/status-xml-w-clones.xml, ha/pcswrap/tests/test_connector.py
https://jts.seagate.com/browse/EOS-16030
Automatic unit tests are written. Tests are green.
1. Unit tests in pcswrap were broken due to #265 
2. `hctl node status --full` JSON counts number of "starting" resources incorrectly if there are multistate (master/slave) resources - like SSPL.
1. Don't rely on role="Started" in pcs status XML output
According to
https://github.com/ClusterLabs/pacemaker/blob/master/xml/resources-3.5.rng#L377
the role can be also "Master" or "Slave". Curious, when a master-slave
resource is added (like SSPL), the corresponding resources never get
roles "Started" - that's why hctl node status will never consider them
as running.
2. Use crm_mon/summary section instead to get number of stopped and
eligible resources. It seems to provide the necessary
numbers …
=> Problem: hctl node status counts wrong 'running' resources

ha/setup/create_cluster.py, ha/setup/create_pacemaker_resources.py
<pre>
<code>
https://jts.seagate.com/browse/EOS-16480
DoD:
We should have a shell script configuring rules for all Cortx services in pacemaker.
Upon executing the script and given that required 3rd party services are up, the Cortx cluster and all resources shall be created.
Stonith is disabled.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Scripts are supposed to be executed by HA mini provisioner during config phase.
</code>
</pre>
<pre>
<code>
2 python scripts implemented:
* to create cluster
* to populate cluster with resources
They are ready to be imported to HA mini provisioner python code. Scripts also can be used as standalone CLI tools.
Dependent from ha/execute module to run pcs commands.
</code>
</pre>
<pre>
<code>
No. Scripts can be fully tested only in integration …
=> EOS-16480: create pacemaker resources on VM

ha/resource/sspl
Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-16878: HA (pcs) did not detect that SSPL had crashed and did not restart it
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Observed that demoted node is taking too much time after the forcefully kill.
</code>
</pre>
<pre>
<code>
Added code changes to remove state file in the stop method and also added couple of improvement
</code>
</pre>
<pre>
<code>
Tested changes in the live setup and observed that sspl service starts immediately after the demotion.
</code>
</pre>
=> EOS-16878: SSPL resource agent improvements

ha/resource/sspl
Signed-off-by: Vijay Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-16878: HA (pcs) did not detect that SSPL had crashed and did not restart it
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Modify start_sspl_service() function for more code readability
</code>
</pre>
<pre>
<code>
Modified start_sspl_service() function to address review comments
</code>
</pre>
<pre>
<code>
Valiadated changes on the hardware setup and it's working as expected
</code>
</pre>
=> EOS-16878: Modify sspl start service function for more code readability

ha/setup/create_pacemaker_resources.py
<pre>
<code>
EOS-17229
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
meta-data query failing.
</code>
</pre>
<pre>
<code>
Found command given in description of ticket is typo
pcs resource create motr-confd-1 ocf:seagate:dynamic_fid_servce_ra service=m0d fid_service_name=confd --group io_group
it is ocf:seagate:dynamic_fid_service_ra
But still problem exist and tried --force
Seen --force is working and resource started with no error even in logs
Crating first patch with --force to unblock and mode debug can be done later
</code>
</pre>
<pre>
<code>
No unit testing provided …
=> EOS-17229: First patch to do force create

ha/cli/cortxha.py, jenkins/rpm/v2/cortx-ha.spec
<pre>
<code>
The cortx HA clis start with the keyword "cortxha".
This needs to be changed to "cortx"
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
The cortx HA clis start with the keyword "cortxha".
This needs to be changed to "cortx"
</code>
</pre>
<pre>
<code>
Renamed the executable file  for the CLI from crotxha to cortx for V2
Modified the help string 
</code>
</pre>
<pre>
<code>
- Verified that for V2, the CLI is displayed as "cortx" . Ex "cortx cluster start" 
-  Verified that the help string also displays "cortx" instead of "cortxha"
-  Verified that for V1, the CLI is displayed as cortxha . Ex cortxha cluster start 
-  Verified that the help string also displays "cortxha " for V1 
- Confirmed that the correct CLI functionality is executed based on …
=> Changes for EOS-17336 Change the cortxha keyword in HA CLIs to cortx

Quick-Start-Guide.rst, jenkins/cicd/cortx-ha-dep.sh
<pre>
<code>
Story Ref (if any): n/a
Fix for CI script and quick start guide
</code>
</pre>
<pre>
<code>
No
cortx-ha-dep.sh script for development invocation on my VM. There is always a small chance that CI will get broken as a result of these updates.
</code>
</pre>
<pre>
<code>
Dev installation described in quick start guide simply does not work because cortx-ha-dep.sh scripts contains mistakes.
</code>
</pre>
<pre>
<code>
Fixed argument parsing and modified program flow for usage cases.
</code>
</pre>
<pre>
<code>
Just run: `sudo jenkins/cicd/cortx-ha-dep.sh -e dev -t <your-github-token>`
It shall work now.
`sudo` is needed due to cortx-utils.
</code>
</pre>
=> Fix CI scripts and quick start guide

jenkins/pyinstaller/v2/requirements.txt
<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-17151
Remove cryptography python dependency for LR-2 cortx-ha
</code>
</pre>
<pre>
<code>
ha_setup can be successfully imported when cortx-utils package is installed.
</code>
</pre>
<pre>
<code>
Package is not used directly. Instead cortx-utils module is used. No need to have it cortx-ha requirements.txt
</code>
</pre>
<pre>
<code>
Remove dependency in LR-2 requirements.txt
</code>
</pre>
<pre>
<code>
N/A
</code>
</pre>
=> EOS-17151: remove cryptography python dependency for LR-2 cortx-ha

setup.py
The presence of setup.py file allows to create a development
installation.
Use `pip3 instal -e ./` command to install cortx-ha to active venv.
Use `pip3 uninstall ha` to remove it.
`python3 setup.py bdist{,_rpm}` shall also work, though they are not an
official way to build cortx-ha package.
<pre>
<code>
Story Ref: https://jts.seagate.com/browse/EOS-18359
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Pyinstaller is used to bundle cortx-ha.
Due to this fact, option with development installation is missing.
It is useful and sometimes crucial for testing.
</code>
</pre>
<pre>
<code>
Add setup.py with distutils invocations to make command pip install -e ./ available
</code>
</pre>
<pre>
<code>
Done on VM. Not used on production environment.
</code>
</pre>
=> EOS-18359: add setup py for development installation

ha/cli/command_factory.py, ha/cli/commands.py, ha/cli/exec/clusterExecutor.py, ha/cli/exec/commandExecutor.py
<pre>
<code>
EOS-16248 User interface for cluster start CLI
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Implement user interface for cluster start CLI
</code>
</pre>
<pre>
<code>
- Code implementation in cluster manager to point to the cluster controller
- Code implementation in CortxClusterManager to process the request provided at CLI level
- Set output to cli of our actual core library function response
</code>
</pre>
<pre>
<code>
-bash-4.2$ sudo cortxha cluster start --all --json
"{\"status\": \"InProgress\", \"msg\": \"Cluster start operation performed\"}"
-bash-4.2$ sudo cortxha cluster start --server --json
"{\"status\": \"InProgress\", \"msg\": \"Cluster start operation performed\"}"
</code>
</pre>
=> EOS-16248 User interface for cluster start CLI

ha/cli/exec/clusterExecutor.py, ha/cli/exec/commandExecutor.py
- Add command line parsing
- Validate arguments
<pre>
<code>
EOS-18115: CORTX-HA : User interface for cluster stop CLI  </code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Implement "cortx cluster stop" CLI for HA   </code>
</pre>
<pre>
<code>
Base framework is already there. Verify cluster add option. . If node is there. Control will go to cluster node add module and eventually to cluster manager
</code>
</pre>
<pre>
<code>
Execute CLI using 
cortx cluster stop <--server | --all>. --server is the default argument.
</code>
</pre>
=> EOS-18115: CORTX-HA : User interface for cluster stop CLI

ha/const.py, ha/core/controllers/pcs/pcs_controller.py
Signed-off-by: Vijaykumar Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-19431
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Observed that current loigc returns the resource failout of the whole cluster but our requirement is to check resource failcount for the requested node.
</code>
</pre>
<pre>
<code>
Added fix to check resource failcount exists for requested node.
</code>
</pre>
<pre>
<code>
Tested changes in the 3 nodes cluster and able to start cluster successfully
</code>
</pre>
=> EOS-19431: fix the issue to check resource fail count for the requested node.

ha/cli/exec/clusterExecutor.py, ha/cli/exec/commandExecutor.py, ha/cli/exec/nodeExecutor.py
<pre>
<code>
https://jts.seagate.com/browse/EOS-16249
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
To add CLI support for node start
</code>
</pre>
<pre>
<code>
- Code implementation to point to the node controller in nodeExecutor
- Code implementation to process the request provided at CLI level via execute method in nodeExecutor
- Set output to cli of our actual core library function response
- Implementation of validate functionality & parse args for the node start functionality.
</code>
</pre>
<pre>
<code>
Positive test:
-bash-4.2$ sudo cortxha node start --nodeid node1 --all
{"status": "Succeeded", "msg": "Node node1, is already in Online status"}
-bash-4.2$ sudo cortxha node start --nodeid node1 --all
{"status": "InProgress", "msg": "Node node1 : …
=> EOS-16249 node start CLI change

conf/mini_provisioner/v2/ha_setup.yaml, conf/mini_provisioner/v2/setup.yaml
<pre>
<code>
Add mini-provisioner prepare command and updated setup.yaml
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
The mini-provisioner prepare command is missing. and path in setup.yaml is not proper. 
</code>
</pre>
<pre>
<code>
Add mini-provisioner prepare command and updated setup.yaml
</code>
</pre>
<pre>
<code>
Successfully tested with single node by running the new command.
</code>
</pre>
=> EOS-19535: Update ha_setup path of setup.yaml

ha/core/controllers/pcs/node_controller.py
Signed-off-by: Vijaykumar Thakkar <vijaykumar.thakkar@seagate.com>
<pre>
<code>
EOS-19431
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
QA has observed that node start operation ignored when node is in standby mode with running resource.
</code>
</pre>
<pre>
<code>
As discussed in the team's chat, I have removed "standby node with running resources" condition and combined with "standby" condition.
</code>
</pre>
<pre>
<code>
Validation done on 3 node cluster and it works fine
</code>
</pre>
=> EOS-19431: Unstandby the node even when it is in standby mode with running resource

ha/remote_execution/remote_executor.py, ha/remote_execution/ssh_communicator.py, ha/setup/ha_setup.py
<pre>
<code>
Story Ref (if any): EOS-19624
Password is exposed during add node
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
We are passing command as it is to log file without masking password during add node.
</code>
</pre>
<pre>
<code>
Here we are creating copy of command then password is masked in that copied command and passed to log fie.
</code>
</pre>
<pre>
<code>
</code>
</pre>
=> EOS-19624 Password is exposed during add node

ha/core/controllers/pcs/node_controller.py
- Remove start functionality from PcsHWNodeController
- Inherit PcsHWNodeController from PcsVMNodeController
<pre>
<code>
https://jts.seagate.com/browse/EOS-20856
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Implement cortx node start on HW environment
</code>
</pre>
<pre>
<code>
1. node start is already implemented for VM environment and this functionality does not differ env to env
2. So, Inherit PcsHWNodeController from PcsVMNodeController
3. Remove start functionality from PcsHWNodeController if its present. So, that call will directly go to base class start.
</code>
</pre>
<pre>
<code>
1. Perform mini provisioning steps
2. Change env to HW in /etc/ha/ha.conf file
3. Execute cortx **node start …
=> EOS-20856: Implement cluster start and stop on HW

conf/etc/v2/ha.conf, ha/resource/dynamic_fid_service_ra.py, ha/resource/service_instances_counter.py, ha/setup/create_pacemaker_resources.py, ha/setup/ha_setup.py, jenkins/rpm/v2/post_install_script.sh, jenkins/rpm/v2/post_uninstall_script.sh
<pre>
<code>
EOS-20697: HA: during bootstrap motr ioservices have dependency on all confd m0d's
Added cortx_message_bus service in the rules.
</code>
</pre>
<pre>
<code>
Yes - on three node VMs.
</code>
</pre>
<pre>
<code>
To implement constraint rules based on number of instances running of a resource, a mechanism is required to count the
running instances. It was achieved by updating node level attributes using attrd_updater.
A new HA service srv_counter is introduced for this purpose.
</code>
</pre>
=> EOS-20697: Rewrite pacemaker rules to accommodate new and future requirements

ha/setup/ha_setup.py, jenkins/rpm/v2/post_install_script.sh
<pre>
<code>
https://jts.seagate.com/browse/EOS-20496
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Validate permissions for log & conf dirs - root user and ha_client user permissions
</code>
</pre>
<pre>
<code>
Validate permissions for log & conf dirs - root user and ha_client user permissions
Add User and Permission validation
R/W for log for root and other user
R/W for conf for root
R for conf for other user
</code>
</pre>
<pre>
<code>
[root@ssc-vm-c-0281 ~]# /opt/seagate/cortx/ha/bin/ha_setup post_install --config 'json:///root/cortx-ha/1nodevmconfig.json' --dev
[root@ssc-vm-c-0281 ~]# getfacl /etc/cortx/ha
getfacl: Removing leading '/' from absolute path names
user::rwx
group::r-x
group:root:rwx …
=> EOS-20496: user group permissions fix

ha/const.py, ha/core/event_analyzer/filter/filter.py
<pre>
<code>
In event_analyzer,  filter the delimiter '>' was not correctly being used to access the Confstore 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
In event_analyzer,  filter the delimiter '>' was not correctly being used to access the Confstore 
</code>
</pre>
<pre>
<code>
In event_analyzer,  filter the delimiter '>' was not correctly being used to access the Confstore 
Corrected the code to use delimiter in the appropriate place 
</code>
</pre>
<pre>
<code>
Using a standalone file and code copied from filter.py, confirmed that the correct string is getting generated to fetch data from Confstore  
</code>
</pre>
=> Changes for EOS-21143 Not able to change delimiter in conf

ha/core/event_analyzer/watcher/watcher.py, ha/test/integration/event_analyzer/test_alert_receiver.py
<pre>
<code>
EOS-19779
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Modify the kafka message consumer offset from 'latest' to 'earliest'
</code>
</pre>
<pre>
<code>
Modified the kafka message consumer offset from 'latest' to 'earliest'
</code>
</pre>
<pre>
<code>
Applied this change on already deployed system and made sure that event analyzer is receiving messages.
</code>
</pre>
=> EOS-19779: Corrected messsage consumer offset

ha/resource/dynamic_fid_service_ra.py, ha/setup/create_pacemaker_resources.py
<pre>
<code>
EOS-21436: motr-confd service getting stopped before motr-ios while stopping the cluster.
Remove deletion of attribute, instead set it to zero to check if timeout for srv_counter happens less frequently.
</code>
</pre>
<pre>
<code>
Yes. On 3-node VM.
</code>
</pre>
=> EOS-21436: Add stop constraints.

ha/core/controllers/pcs/cluster_controller.py, ha/setup/ha_setup.py
- Add interface to destroy the cluster in the cluster manager
- Use this interface in ha_setup to destroy the cluster in
case of HA mini-provisioner error
<pre>
<code>
https://jts.seagate.com/browse/EOS-18250
</code>
</pre>
<pre>
<code>
WIP
</code>
</pre>
<pre>
<code>
Provide destroy cluster interface in cluster manager
</code>
</pre>
<pre>
<code>
- Provide stop interface in cluster controller 
</code>
</pre>
<pre>
<code>
WIP 
</code>
</pre>
=> EOS-18250: Cluster Manager destroy cluster

conf/mini_provisioner/v2/setup.yaml, ha/setup/ha_setup.py, ha/setup/post_disruptive_upgrade.py
<pre>
<code>
EOS-17922
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
No pre-disruptive upgrade hooks implemented.
</code>
</pre>
<pre>
<code>
Provisioner setup.yaml format supports configurable pre and post hooks
for upgrade procedure.
Respective commands were added to HA mini provisioner.
So, perform_post_upgrade was moved from `upgrade` command to new
`post_upgrade` command.
Cluster-related changes in pacemaker are done only when mini-provisioner
is invoked on cluster level (provisioner env variables are being
checked).
Configuration backup is done on every node (node level).
</code>
</pre>
<pre>
<code>
This code requires QA testing with upgrade scenario.
Provisioner commands can be used to verify which commands will be invoked for each level.
See: …
=> EOS-17922: Add hooks for pre and post disruptive upgrade routines

ha/const.py, ha/core/cluster/cluster_manager.py, ha/core/controllers/pcs/node_controller.py, ha/setup/ha_setup.py
<pre>
<code>
Story Ref (if any): EOS-20855
F-97D - Cluster: Factory Reset: Pre-Factory
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
1. F-97D - Cluster: Factory Reset: Pre-Factory
2. Copy "cortx_ha_log.conf" file under " /etc/logrotate.d/" directory.
</code>
</pre>
<pre>
<code> 
system back to pre-factory stages when --pre-factory option is used with cleanup command
Copied "cortx_ha_log.conf" file under " /etc/logrotate.d/" directory.
</code>
</pre>
<pre>
<code>
Tested & confirmed that " /etc/logrotate.d/cortx_ha_log.conf" created after post_install command.
and cleanup works fine with --pre-factory option.
</code>
</pre>
=> EOS-20855:Mini-provisioner cleanup command fails if node is in standby

ha/cli/cortxha.py, ha/core/controllers/pcs/cluster_controller.py, ha/setup/ha_setup.py
<pre>
<code>
3N VM-Deployment Failed in HA 
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
3N VM-Deployment Failed in HA . Possible cause is one/more of the nodes that were getting added in the cluster during cluster creation did not come online  before further steps in ha_setup config phase were carried out 
</code>
</pre>
<pre>
<code>
Added check in _add_node, _add_node_remotely  to wait for the node to come online before proceeding
</code>
</pre>
<pre>
<code>
- On 3 node VM deployment confirmed that in happy path cluster deployment is successful
- Instrumented code added to cause failure. i.e node status does not change to Online after addition. Confirmed that exception raised in this case and node not added to cluster 
</code>
</pre>
=> EOS-21080: 3N VM-Deployment Failed in HA for the build Main#1268

ha/setup/ha_setup.py, ha/setup/post_disruptive_upgrade.py
<pre>
<code>
EOS-23039: SW upgrade failed on HA upgrade branch
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Upgrade path code is missing ios_instances argument which gets passed as an argument to create_all _resources and which is  needed in post_upgrade path as well
</code>
</pre>
<pre>
<code>
Added the code to get ios_instances wherever is needed  
</code>
</pre>
<pre>
<code>
For now, just installed the RPM and performed the mini prov steps and checked the cluster status
</code>
</pre>
=> EOS-23039: SW upgrade failed on HA upgrade branch

ha/setup/create_pacemaker_resources.py, ha/setup/ha_setup.py
<pre>
<code>
EOS-22972: Cluster not starting up after successful 3N HW deployment
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- Cluster not starting up after successful 3N HW deployment due to getting stonith config before updating the ha conf file.
</code>
</pre>
<pre>
<code>
- Updated code to return the config after updating the env in ha conf file. 
</code>
</pre>
<pre>
<code>
**********************[VM config]****************************
[root@sm34-r6 ~]# ha_setup post_install --config 'json:///root/example_config.json' --dev
Mini Provisioning post_install configured successfully.
[root@sm34-r6 ~]# ha_setup config --config 'json:///root/example_config.json' --dev
Mini Provisioning config configured …
=> EOS-22972: Cluster not starting up after successful 3N HW deployment

ha/setup/ha_setup.py
<pre>
<code>
https://jts.seagate.com/browse/EOS-23039
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Basic problem was, some code of getting ios_instaces and passing it to create_resources through post_upgrade routine was missing. This was fixed using earlier PR but that PR had a mistake of passing the arguments (there was a order mismatch). Hence correcting those order. 
</code>
</pre>
<pre>
<code>
Pass every argument as named argument with proper order
</code>
</pre>
<pre>
<code>
RPM installation
Perform Pre and Post upgrade with some changes that will make the upgrade testing  
</code>
</pre>
=> SW upgrade failed on HA upgrade branch

ha/core/event_manager/event_manager.py, ha/util/consul_kv_store.py
<pre>
<code>
Need to implement the functions get_events, message_type
</code>
</pre>
<pre>
<code>
No , testing done on deployed setup using python files directly
</code>
</pre>
<pre>
<code>
Implement the functions get_events, message_type
</code>
</pre>
<pre>
<code>
Implemented functionality for get_events, message_type
</code>
</pre>
<pre>
<code>
On a 3 node deployment  ddded keys to consul directly.
Tested by executing the event_manager.py file directly that 
For both function calls
-  Correct value returned when matching key is found
-  None / empty list returned when exact matching key is not found
-  All success / failure paths in code tested ( single key / multiple keys with same prefix / no matching keys present in consul etc)
</code>
</pre>
=> Changes for EOS-22165 Implement event manager interface to list (get_events) and get message type APIs

ha/setup/ha_setup.py
<pre>
<code>
EOS-23192: 3 Node automated HW deployment fails on Jenkins
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
3 Node automated HW deployment fails on Jenkins
</code>
</pre>
<pre>
<code>
- Needs to cleanup resources before creating stonith resource for other nodes
</code>
</pre>
<pre>
<code>
2021-08-02 17:49:05 ha_setup [44959]: ERROR [run_cmd] cmd: pcs -f /var/log/seagate/cortx/ha/cortx-r2-cib.xml stonith create stonith-srvnode-1 fence_ipmilan ipaddr=10.237.65.161             login=bmcadmin passwd=adminBMC! pcmk_host_list=srvnode-1 pcmk_host_check=static-list             lanplus=true auth=PASSWORD power_timeout=40 verbose=true             op monitor interval=10s meta failure-timeout=15s --group …
=> EOS-23192: 3 Node automated HW deployment fails on Jenkins

ha/setup/create_pacemaker_resources.py, ha/setup/ha_setup.py
<pre>
<code>
EOS-23330: Stonith resource creation is getting overlapped in config phase on other than first node
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
EOS-23330: Stonith resource creation is getting overlapped in config phase on other than first node
</code>
</pre>
<pre>
<code>
- Added code to create stonith resources for all nodes in config phase execution on first node
- Changed code a bit, whenever adding a node to the cluster we are configuring stonith for that node. Its creating stonith resources, but stonith_enable is false at that time.
- Before creating any stonith resource for any node we first checking its already present or not, if not then only we create the stonith resource for that …
=> EOS-23330: Stonith resource creation is getting overlapped in config phase on other than first node

conf/mini_provisioner/v2/setup.yaml, conf/mini_provisioner/v2/support.yaml, jenkins/build_with_pyinstaller.sh
<pre>
<code>
EOS-23626 : Create support.yaml for HA
</code>
</pre>
<pre>
Yes, on single node and 3 node VM. Refer unit cases section for tests.
</pre>
<pre>
<code>
With addition of upgrade related entries in setup.yaml, YAML parsing of setup.yaml is broken (but provisioner is capable of handling this).
Command for component specific support bundle generation is in setup.yaml
Due to broken parsing, support bundle generation is at risk and a quick remedy is required.
</code>
</pre>
-Create support.yaml file which will have the "support_bundle" entry from setup.yaml 
-Install this support.yaml file at the same location where current setup.yaml file resides after installation.
-  Automated single node deployment passed : …
=> EOS-23626 : Create support.yaml for HA

ha/core/controllers/pcs/node_controller.py
<pre>
<code>
Replaced the _get_node_name method with ConfigManager.get_node_name
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Replaced the _get_node_name method with ConfigManager.get_node_name
</code>
</pre>
<pre>
<code>
Replaced the removed  _get_node_name method with ConfigManager.get_node_name
</code>
</pre>
<pre>
<code>
</code>
</pre>
=> EOS-22373:  _get_node_name issue

ha/core/event_manager/event_manager.py
<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-24001
EOS-24001: Get message type throws an Error
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
In get message type previously we are considering component type as string & because of that when we are calling component.value it returns error message.
</code>
</pre>
<pre>
<code>
component type changed to SUBSCRIPTION_LIST.
</code>
</pre>
<pre>
<code>
>>> from ha.core.event_manager.event_manager import EventManager
>>> from ha.core.event_manager.subscribe_event import SubscribeEvent
>>> event_manager = EventManager.get_instance()
>>> cluster = SubscribeEvent("enclosure:hw:controller", ["online", "failed", "offline"])
<h4>Test 1 : Subscribe Event </h4> …
=> EOS-24001: Get message type throws an Error

ha/core/config/config_manager.py, ha/core/controllers/pcs/cluster_controller.py, ha/core/controllers/pcs/node_controller.py, ha/setup/ha_setup.py
<pre>
<code>
EOS-23620: Secondary nodes (HW) stonith seen during deployment
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
If the stonith is enabled before the full cluster configuration, stonith behaves weirdly and does the node power off 
</code>
</pre>
<pre>
<code>
Enable stonith after the cluster start
</code>
</pre>
<pre>
<code>
[root@sm17-r18 cluster]# pcs property list
Cluster Properties:
cluster-infrastructure: corosync
cluster-name: cortx_cluster
dc-version: 1.1.23-1.el7-9acf116022
have-watchdog: false
last-lrm-refresh: 1629883606
stonith-enabled: false
[root@sm17-r18 cluster]# cortx cluster start
{"status": "InProgress", "output": "Cluster start operation performed", "error": ""}[root@sm17-r18 cluster]#
[root@sm17-r18 cluster]# pcs property list …
=> EOS-23620: Secondary nodes (HW) stonith seen during deployment

ha/core/controllers/pcs/cluster_controller.py, ha/setup/ha_setup.py
<pre>
<code>
EOS-23620: Secondary nodes (HW) stonith seen during deployment
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
If the stonith is enabled before the full cluster configuration, stonith behaves weirdly and does the node power off 
</code>
</pre>
<pre>
<code>
Enable stonith after the cluster start
</code>
</pre>
<pre>
<code>
[root@sm17-r18 cluster]# pcs property list
Cluster Properties:
cluster-infrastructure: corosync
cluster-name: cortx_cluster
dc-version: 1.1.23-1.el7-9acf116022
have-watchdog: false
last-lrm-refresh: 1629883606
stonith-enabled: false
[root@sm17-r18 cluster]# cortx cluster start
{"status": "InProgress", "output": "Cluster start operation performed", "error": ""}[root@sm17-r18 …
=> EOS-23620 : Fix for enable stonith after cluster start

ha/core/event_manager/error.py, ha/core/event_manager/event_manager.py
<pre>
<code>
EOS-24089: Unsubscribe the event twice throws an improper exception
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Unsubscribe the event twice throws an improper exception
</code>
</pre>
<pre>
<code>
Handle exception properly to show proper error message to client
</code>
</pre>
<pre>
<code>
>>> from ha.core.event_manager.event_manager import EventManager
>>> from ha.core.event_manager.subscribe_event import SubscribeEvent
>>> cluster = SubscribeEvent("enclosure:hw:controller", ["online", "failed"])
>>> test = event_manager.unsubscribe("csm",[cluster])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'event_manager' is not defined
>>> event_manager = …
=> EOS-24089: Unsubscribe the event twice throws an improper exception

ha/k8s_setup/ha_setup.py, ha/k8s_setup/ha_start.py, ha/monitor/k8s/object_monitor.py, ha/test/cluster_role.yaml, ha/test/cluster_role_binding.yaml, ha/test/ha_monitor_service_account.yaml
- Containerize K8S monitor service
Implementation will be done as part of https://jts.seagate.com/browse/EOS-25520. 
1. Crated a simple POD file which will use the cortx-all image and which will have my branch code
2. Performed exec to the container. As, right now, its printing the events, manually executed the entrypoint
sh-4.2# python3 /usr/lib/python3.6/site-packages/ha/monitor/k8s/monitor.py
Received Node-alert
Thread = Monitor-node-Thread Alert = {'_resource_type': 'k8s:node', '_resource_name': 'ssc-vm-g3-rhev4-1313.colo.seagate.com', '_event_type': 'online', '_k8s_container': None, '_pod': None, '_node': None, '_is_status': True}
Thread …
=> EOS-25518: [K8S:RAW] Containerize K8S monitor

ha/core/event_analyzer/filter/filter.py, ha/fault_tolerance/fault_tolerance_driver.py, ha/k8s_setup/const.py, ha/k8s_setup/ha_setup.py, ha/monitor/k8s/alert.py, ha/monitor/k8s/parser.py
Implement Fault Tolerance service
https://seagate-systems.atlassian.net/wiki/spaces/~445727228/pages/688881888/Design+page
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/730890496/Fault+tolerance+LLD
Testing:
1. Started k8s monitor so that alerts will be pushed to k8s_event topic on message bus
2 started fault_tolerance service which will listen on k8s_event topic of message bus
3. Deleted the POD with label as **cortx-data**
4. Checked the alert is received or not in fault_tolerance log file 
[root@ssc-vm-g3-rhev4-1313 cortx-ha-1]# tail -f /var/log/seagate/cortx/ha/fault_tolerance_driver.log
2021-11-02 05:46:15 …
=> EOS-24275: Implement fault tolerance driver service

ha/core/system_health/system_health.py, ha/k8s_setup/ha_setup.py
Create create resource map during bootstrap from the system health module
Events are received by system health from the k8s_monitor.
At the beginning, HA needs to identify the nodes (i.e. k8s pods) that are running in the system for which alerts need to be generated. This list needs to be maintained in confstore.  For this time duration, alerts should not be sent to Hare.
To get this list, system health uses timeout value available in ha.conf and alerts coming from k8s monitor are absorbed by system health. Hare events are not generated
After timeout is reached, alerts received after that are sent to hare
-  [x] Coding conventions are followed and code is consistent : yes
=> Changes for EOS-26578  [K8S:RAW] System health bootstrap changes required for K8S Alert

ha/k8s_setup/ha_setup.py, ha/monitor/k8s/const.py, ha/monitor/k8s/parser.py
Signed-off-by: mukhtar inamdar <mukhtar.inamdar@seagate.com>
- finalize the machine id key as it is added in the pod definition
- so needs to remove from conf and get the actual machine-id from the event to alert.resource_name
-  Finalize the machine id key as it is added in the pod definition.
-  Removed from conf
- Added code to get the actual machine-id.
-  Fetch like this: event['raw_object']['metadata']['labels']['cortx.io/machine-id']
- **Tested by running the monitor service through python file, used rpm to install inside POD.**
- execute the monitor code and print the pod events (i.e. cortx node event)
- see below print logs
> sh-4.2# python3 /usr/lib/python3.6/site-packages/ha/monitor/k8s/monitor.py
---------------------------host------------------------- …
=> EOS-26559 added constant machine id key.

ha/k8s_setup/const.py, ha/k8s_setup/ha_setup.py
- HA POD Health-monitor container failing for consul enpoints[0] not reachable
-  should not use console enpoints[0] directly instead search the HTTP console end point and then use it.
- cluaster.conf will have a list of endpoints out of which needs to filter and take HTTP console endpoint and then use it.
[test_scenarios_ha-monitor-logs_EOS-27071.txt](https://github.com/Seagate/cortx-ha/files/7767395/test_scenarios_ha-monitor-logs_EOS-27071.txt)
*------------------------------------------
sample endpoint entries of consul config from cluster.conf
*------------------------------------------
...
external:
consul:
admin: admin
endpoints:
- tcp://consul-server.default.svc.cluster.local:8301
-
- HTTP
- HTTP:
- http://
- http://127.0.0.1:8500
- …
=> Eos 27071 : HA POD Health-monitor container failing for consul enpoints[0] not reachable

ha/fault_tolerance/cluster_stop_monitor.py, ha/fault_tolerance/fault_monitor.py, ha/fault_tolerance/fault_tolerance_driver.py, ha/k8s_setup/ha_setup.py, ha/monitor/k8s/parser.py
Signed-off-by: ArchanaLimaye <archana.limaye@seagate.com>
- Current fault tolerance service expects and can receive messages over message bus only from the k8s monitor service 
- The "cluster stop" message will be sent by CSM via message bus and fault tolerance needs to be able to receive this message
- 
Modified the fault tolerance to start 2 watchers; one for messages from k8s monitor (topic cluster_event), other for messages from CSM (topic cluster_stop)
=> Changes for EOS-27056 Mechanism to receive stop message from CSM in case of cluster stop

ha/k8s_setup/ha_setup.py
Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
- EOS-27248: added support for Mock Upgrade Miniprovisioner for HA in ha_setup 
-  Ticket ref: https://jts.seagate.com/browse/EOS-27248 
=> EOS-27248: support for Mock Upgrade Miniprovisioner for HA

ha/const.py, ha/k8s_setup/const.py, ha/k8s_setup/ha_setup.py
Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>
- EOS-27303: Log Location for HA should be picked up from confstore
-  Get log location from /etc/cortx/cluster.conf [cortx>common>storage>log] and store all location as same place.
=> EOS-27303: Log Location for HA should be picked up from confstore.

ha/test/integration/test_conf_store_search_api.py, ha/util/conf_store.py
Signed-off-by: ArchanaLimaye <archana.limaye@seagate.com>
- Need to get cluster cardinality using confstore APIs
Using the confstore APIs, got the list of (and machine ids of) data and server pods.
This list and the count stored in consul 
Fault tolerance LLD updated
=> EOS-26969 Implement logic to get data and storage pod information from ConfStore

ha/k8s_setup/ha_setup.py, ha/monitor/k8s/monitor.py
…fstore to filter the API server alert
- Use conf store search API HA wrapper class to get the cluster
cardinality(list of machind_ids).
- Use cortx.io/machine-id label of a Node to match its value with machine_id
list fetched from above API to filter the alert.
- Remove hardcoded label from ha_setup
https://jts.seagate.com/browse/EOS-26971
Use list of machine_ids of a data and server POD to filter the API server alert in HA monitor service.
- Use conf store search API wrapper class to get the cluster cardinality(list of machind_ids).
- Use **cortx.io/machine-id** label of a Node to match the value of its with list fetched from above API to filter the alert.
- Based on the fact that every data and server pod will have …
=> EOS-26971: Modify monitor service to use machine ids fetched from confstore to filter the API server alert

ha/fault_tolerance/cluster_stop_monitor.py, ha/test/integration/test_sigterm_to_ha_services.py
…tween CSM and HA
Signed-off-by: mukhtar inamdar <mukhtar.p.inamdar@seagate.com>
- EOS-27939 Integration issue for message 'start_cluster_shutdown' between CSM and HA
-  use 1 (integer value) instead '1' (string value)
- [] Testing was performed with RPM
Tested with CSM as well as test script already added in test
csm calls:
----------------------------------- Login call ---------------------------------------------------------
post: https://ssc-vm-g4-rhev4-0247.colo.seagate.com:31169/api/v2/login?debug
body (json): {"username": "cortxadmin","password": "Cortxadmin@123"}
------------------------------------- Result -----------------------------------------------------------
Authorization: Bearer 4f4bc005b4e240a594b4ff4b16aac22f …
=> EOS-27939 : Integration issue - set value 'start_cluster_shutdown' to 1 (in integer format).

ha/core/config/config_manager.py, ha/k8s_setup/ha_start.py
- Log redirection to console
-  Redirect log to stdout and stderr
driver_process.stdout.readline() allow to capture buffer console output of child process in parent process
and poll check if child process is running or not.
So if child process is running readline will get output and print it in console.
```
while True:
output = driver_process.stdout.readline()
if driver_process.poll() is not None:
break
if output:
print(output.strip().decode("utf-8"))
exit(driver_process.poll())
```
=> EOS-26085: Redirect log to console

ha/monitor/k8s/object_monitor.py, ha/monitor/k8s/parser.py, ha/test/integration/k8s_monitor/test_no_duplicate_alerts.py
CORTX-28560 - k8s_monitor is repeating previously sent alert event there is no status change on monitoring objects.
CORTX-29057 - Unpacking issue with Event parser when it returns None
CORTX-28560 - Fix is to publish only new alert by checking whether incoming alert is already sent or not.
CORTX-29057 - Return required number of values as client code expects
Test is added. Logs are also validated.
**Log:** https://jts.seagate.com/secure/attachment/505658/DEV_fix_log_23FEB2022.txt
=> CORTX-28560 & CORTX-29057 : Fix duplicate events published from k8s_monitor & Event parser issue

ha/monitor/k8s/object_monitor.py, ha/test/integration/k8s_monitor/test_no_duplicate_alerts.py
The timestamp field is removed from alert after validating it using is_published_alert method.
Before modifying the actual alert, must do deepcopy of the actual alert and proceed.
```
******** Testing K8s Not Publishing Duplicate Alerts ********
2022-02-28 06:54:26 test_k8s_resource_monitor [564]: INFO [init] Started logging for service test_k8s_resource_monitor
Producer id: mock_producer, message_type: mock_message, partition: 1
2022-02-28 06:54:26 test_k8s_resource_monitor [564]: INFO [__init__] Initialization done for pod monitor
Publishing alert..
{'event': {'header': {'version': '1.0', 'timestamp': '112255', 'event_id': '11225568919c5ba8f88ad24cc18f632a75de115aca'}, 'payload': {'source': 'monitor', 'cluster_id': 'None', …
```
=> CORTX-29106: Alert is getting modified and timestamp field is not present in published alert

jenkins/build.sh
-  cortx-ha package generation is failing in Rocky Linux 8.4. [build.sh](https://github.com/Seagate/cortx-ha/blob/main/jenkins/build.sh#L77) uses `x86_64` architecture for cortx-ha package. As cortx-ha contains Python scripts this should be arch indepndent. Removed `--force-arch x86_64` option from `python3.6 setup.py bdist_rpm bdist_rpm` command
=> CORTX-27894 - Use noarch architecture for HA package.

ha/core/system_health/system_health.py
CORTX-27679: on new setup if data pod scale to 0 and then 1 no online event is sent to hare
System Health is updating health status after comparing new event and stored event.
While processing any new event, check event_type in new event is online. 
If new event is online, change stored event event_type to failed. Such that failed event will be reported first and then online event will be next.
```
kubectl scale deploy cortx-data-ssc-vm-rhev4-1667 --replicas 0
2022-03-01 20:54:09 health_monitor [7]: INFO [publish] Sending action event {'event': {'header': {'version': '1.0', 'timestamp': '1646168049', 'event_id': '1646168049a2147e3b6f394b03899cad8b6b435fac'}, 'payload': {'source': 'monitor', 'cluster_id': …
```
=> CORTX-27679: on new setup if data pod scale to 0 and then 1 no online event is sent to hare

ha/core/event_analyzer/filter/filter.py, ha/core/event_analyzer/parser/parser.py, ha/k8s_setup/ha_setup.py
Enhance parser and filter of event analyzer for disk and cvgs
Modify filter of event analyzer which will also filter disk and cvg alert. For that, ha.conf can be modified with list of required resource type as ['node', 'disk', 'cvg'] and then this list can be checked against incoming resource type and alert can be filtered. Parser can be modified to skip the check for specific info generation id for resource type other than "node"
Testing detais:
1. Modified ha.conf
CLUSTER:
resource_type:
- node
- disk
- cvg
CLUSTER_STOP_MON:
consumer_group: cluster_mon
consumer_id: '2'
message_type: cluster_stop
COMMON_CONFIG:
cluster_id: …
=> CORTX-28973: Enhance parser and filter of event analyzer for disk and cvgs

ha/k8s_setup/const.py, ha/test/integration/test_conf_store_search_api.py, ha/util/conf_store.py
- Write wrappers to get disk and cvg ids from gconf
-  Added 3 functions to:
Return list of CVGs for any given node using search APIs
Return list of disks for any given node and CVG using search APIs
Return list of disks for any given node using search APIs
=> CORTX-28892 : Write wrappers to get disk and cvg ids from gconf

ha/k8s_setup/const.py, ha/util/conf_store.py, ha/util/health_generator/README.md
HA is not able to detect events for server nodes because monitor service requires list of ids(machine-ids) that can be monitored. List does not contain server node machine-ids because there is a change in cluster.conf. Previously, cluster.conf has ha-proxy service listed which was used to identify server pods. But, now, s3 is replaced by rgw now and there will not be any services in rgw as of now.
https://jts.seagate.com/browse/CORTX-27961
Use COMPONENT_RGW constant defined in cortx-utils to identify server pod. server pod config will be like this:
9f4033f2f0304859b175ae9680c28a8d:
cluster_id: 1a3acac8233d425c8dbfad522a99feca
components:
- name: utils
- name: hare
- name: rgw
hostname: cortx-server-headless-svc-ssc-vm-g4-rhev4-0582
name: cortx-server-headless-svc-ssc-vm-g4-rhev4-0582 …
=> Cortx-27961: [ConfStore search API] Use COMPONENT_RGW instead of SERVICE_S3_HAPROXY to identify server pods

ha/monitor/k8s/object_monitor.py, ha/test/integration/k8s_monitor/test_no_duplicate_alerts.py
CORTX-28560: Alert publish validation skipped due to new change in schema
- Repeating already published k8s_monitor events 
Previously Event.json returned,
{'event': { 'header': {}, 'payload': {} }}
Now,
"{ 'header': {}, 'payload': {} }"
[CORTX-28560](https://jts.seagate.com/browse/CORTX-28560)
```
[root@cortx-ha-headless-svc ~]# python3 test_no_duplicate_alerts.py
******** Testing K8s Not Publishing Duplicate Alerts ********
2022-03-22 08:35:05 test_k8s_resource_monitor [360]: INFO [init] Started logging for service test_k8s_resource_monitor
Producer id: mock_producer, message_type: mock_message, partition: 1
2022-03-22 08:35:05 test_k8s_resource_monitor [360]: INFO [__init__] Initialization done for pod monitor
Publishing …
```
=> CORTX-28560: Fix multiple events publish issue (Alert publish validation skipped due to new change in schema)

ha/k8s_setup/ha_start.py
Signed-off-by: Mukhtar Inamdar <mukhtar.p.inamdar@seagate.com>
- Add debug option to HA_start
-  Add debug option to HA_start (-d/--debug)
-  updated and corrected usage
- added flushing to ha_start
[test_ha_start_debug_option_3.txt](https://github.com/Seagate/cortx-ha/files/8371749/test_ha_start_debug_option_3.txt)
[Debug option for cortx-ha](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/956891431/Debug+option+for+cortx-ha)
=> CORTX-28313 : Add debug option to HA_start

ha/const.py, ha/core/system_health/system_health.py, ha/core/system_health/system_health_manager.py, ha/fault_tolerance/fault_tolerance_driver.py, ha/k8s_setup/ha_start.py, ha/util/conf_store.py, ha/util/consul_kv_store.py
1. [CORTX-29597](https://jts.seagate.com/browse/CORTX-29597) - (SystemHealth) Update HA conf store wrappers to get disk/CVG resource Ids from consul key
2. [CORTX-30455](https://jts.seagate.com/browse/CORTX-30455) - HA container is crashed due to missing debug validation in ha_start.py
Code that was added to get cvg ids in system health process_event  function should be removed (added in PR https://github.com/Seagate/cortx-ha/pull/674/)
While testing above work, found container crash issue due to debug option validation in ha_start.py This PR includes that fix as well.
Remove /etc/cortx/cluster.conf dependency and get cvg_id from SystemHealth consul key.
https://jts.seagate.com/secure/attachment/511768/disk_test.txt …
=> CORTX-29597 CORTX-30455 : (SystemHealth) Update HA conf store wrappers to get disk/CVG resource Ids from consul key & Adding debug check in ha_start

ha/test/main.py
-  CORTX-29037 : Remove 'pytest' dependency
-  cortx-ha granular image creation is failing due to newly added package `pytest`.  As per new HA test framework, pytest package is not required so removing pytest package from ha requirements ( for creation of granular image )
Note :  Most of the testcases are failing due to unknown reason ( either it's a legacy code Or design changes )
[results_with_pytest.txt](https://github.com/Seagate/cortx-ha/files/8390289/results_with_pytest.txt)
[results_with_unittest.txt](https://github.com/Seagate/cortx-ha/files/8390295/results_with_unittest.txt)
=> CORTX-29037 : Remove 'pytest' dependency

ha/core/system_health/system_health.py, ha/fault_tolerance/const.py, ha/fault_tolerance/fault_monitor.py
- Any 'source' based checks in fault_tolerance should be enhanced to accept 'csm' as a source for the events
-  Currently no checks present in HA for source filed, which are applicable for csm "failed" event.
-  Add "source" & "message_type" constants for CSM.
[test_results.txt](https://github.com/Seagate/cortx-ha/files/8462020/test_results.txt)
=> CORTX-30057 : HA should accept events from CSM for resource status

ha/core/system_health/system_health.py
Signed-off-by: gauri.bhosale <gauri.bhosale@seagate.com>
- When pod is restarted via replicas or kubectl delete, pod_restart count is not set properly.
- 
- system_health status checked incoming genericId and stored genericId if its not same 
checked for status but status not only my online it may 'starting' also  
- https://jts.seagate.com/secure/attachment/513156/Test_Results.txt
Testing result :https://jts.seagate.com/secure/attachment/513156/Test_Results.txt
=> CORTX-29399 : When pod is restarted via replicas or kubectl delete, pod_restart count is not set properly.

ha/util/conf_store.py
Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Get machine-id for control_node.
- Added function to fetch machine-id from control_node in HA's conf_stor.py file
https://jts.seagate.com/secure/attachment/513161/test_results.txt
*Note:  This PR is duplicate of PR: https://github.com/Seagate/cortx-ha/pull/683
All review comments were received , discussed, closed on PR 683 and all approvals are also there on that same PR
However when the base branch was changed from main to fault_k8s PR 683 started showing DCO failures.  This fresh PR is started on fault_k8s main directly with same code changes to avoid DCO failures*
=> CORTX-29884: Get machine-id for control_node.

ha/core/event_manager/resources.py, ha/core/system_health/const.py, ha/core/system_health/system_health.py, ha/k8s_setup/ha_setup.py, ha/monitor/k8s/parser.py
added functional_type into specific_info during mini provisioning
later specific_info will be overwritten in k8s monitor and system_health, that will be handle in another PR.
Signed-off-by: gauri.bhosale <gauri.bhosale@seagate.com>
- https://jts.seagate.com/browse/CORTX-29931
- detect functional_Type using confstoreAPI
- add functional_type in json specific_info during mini provisioning
-
- https://jts.seagate.com/secure/attachment/514398/Test_Results.txt
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD#specific_info%3A
https://jts.seagate.com/secure/attachment/514398/Test_Results.txt
=> CORTX-29931 : Enhance System health schema for control node 

ha/core/event_manager/event_manager.py, ha/core/health_monitor/monitor_rules_manager.py, ha/test/integration/health_monitor/test_event_subscriber.py
HA subscription keys now include functional type as well such as 'date', 'server', 'control'. So, the new keys will look like:
cortx>ha>v2>events>node>server>offline
cortx>ha>v2>events>subscribe>hare:["node>server>offline"]
Need to verify if this is happening correctly or not. Also, after un-subscription,
keys and values needs to be deleted properly. To achieve this, SubscribeEvent class
will accept one more List parameter now which contains functional_type list.
Ex:
SubscribeEvent('node', ["online", "offline", "failed"], ['data'])
This means, someone is subscribing to date node alerts for the events online, failed
and offline
**https://jts.seagate.com/browse/CORTX-29991**
Modify HA mini provisioning to make new subscription …
=> Cortx-29991: Event Subscription: API enhancements

ha/core/system_health/status_mapper.py, ha/core/system_health/system_health.py
System health update for control node
For control node, the node health state needs to be consumed and updatedas it is received by HA. For now, the node health state is "unknown". After, first time, the state is marked as "starting". And then hare updates HA whether that POD is ready or not and then HA marks it as ONLINE in system health. But, HARE will not be informing HA regarding control node. Hence, code update is needed when its a control node alert, consume and update the state as it is.
For control node, consume the alert state as it is. Stopped updating the health.
https://jts.seagate.com/secure/attachment/516264/CORTX-29933_Test_Results.txt
Checklist for …
=> CORTX-29933: System health update for control node

ha/k8s_setup/ha_setup.py
Signed-off-by: ArchanaLimaye <archana.limaye@seagate.com>
Workaround to reduce consul access time during HA mini provisioning
Workaround to reduce consul access time during HA mini provisioning
All types of consul key creation stopped for disk and cvg resources
=> CORTX-29667 Workaround to reduce consul access time during HA mini provisioning

ha/core/config/config_manager.py, ha/core/health_monitor/monitor_rules_manager.py, ha/k8s_setup/ha_setup.py, ha/util/consul_kv_store.py
Signed-off-by: Mukhtar Inamdar <mukhtar.p.inamdar@seagate.com>
replicate the pull request: https://github.com/Seagate/cortx-ha/pull/712
All comments from #712: https://jts.seagate.com/secure/attachment/518021/CORTX-29667-comments-pull-%23712.pdf
(JSON): https://jts.seagate.com/secure/attachment/518023/CORTX-29667-comments.json
- ha_setup takes a long time for every consul put() call during mini provisioning.
-  enable transaction push of kv consul for bulk push (performance change)
-  implement caching for put call calls and put them all at a once
- Testing: https://jts.seagate.com/secure/attachment/517504/CORTX-29667.log.v3.txt
Note: debug logs are converted to …
=> CORTX-29667 : Added caching in ConsulKvStore for enabeling batch put
